"""Git sync routes — auto-push generated code to GitHub."""

from __future__ import annotations

import logging
import os
import uuid
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["git_sync"])


def _get_auth():
    from server import get_current_user

    return get_current_user


def _get_optional_user():
    from server import get_optional_user

    return get_optional_user


def _get_db():
    import server

    return server.db


async def _get_task(task_id, user):
    from server import _get_task_for_user

    return await _get_task_for_user(task_id, user)


class GitSyncBody(BaseModel):
    project_id: Optional[str] = None
    task_id: Optional[str] = None
    repo_name: Optional[str] = None  # custom repo name (defaults to project name)
    private: Optional[bool] = True


@router.post("/git-sync/push")
async def git_sync_push_to_github(body: GitSyncBody, user: dict = Depends(_get_auth())):
    """
    Auto-create a GitHub repo and push the build's generated files.
    Requires GITHUB_TOKEN env var (server-level) or user's stored github_token.
    Returns: { repo_url, clone_url, pushed_files }
    """
    import base64
    import re

    import httpx

    db = _get_db()
    # Resolve files from project or task
    files: dict = {}
    project_name = body.repo_name or "crucibai-app"

    if db is not None:
        if body.project_id:
            proj = await db.projects.find_one(
                {"id": body.project_id, "user_id": user["id"]}
            )
            if not proj:
                raise HTTPException(status_code=404, detail="Project not found")
            files = proj.get("deploy_files") or {}
            project_name = body.repo_name or (proj.get("name") or "crucibai-app")
        if not files and body.task_id:
            task = await _get_task(body.task_id, user)
            if task:
                files = task.get("files") or {}
                project_name = (
                    body.repo_name or (task.get("prompt") or "crucibai-app")[:40]
                )

    if not files:
        raise HTTPException(
            status_code=400, detail="No generated files found. Run a build first."
        )

    # Get GitHub token (user stored > env)
    u = await db.users.find_one({"id": user["id"]}, {"deploy_tokens": 1}) if db else {}
    github_token = (u.get("deploy_tokens") or {}).get("github") or os.environ.get(
        "GITHUB_TOKEN"
    )
    if not github_token:
        raise HTTPException(
            status_code=402,
            detail="Add your GitHub token in Settings → Deploy integrations to enable Git sync.",
        )

    # Sanitize repo name
    safe_name = (
        re.sub(r"[^a-zA-Z0-9_\-]", "-", project_name.strip()).strip("-")[:100]
        or "crucibai-app"
    )
    is_private = body.private if body.private is not None else True

    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async with httpx.AsyncClient(timeout=30.0) as client:
        # 1. Get authenticated user's login
        me_r = await client.get("https://api.github.com/user", headers=headers)
        if me_r.status_code != 200:
            raise HTTPException(
                status_code=502, detail="GitHub token invalid or expired."
            )
        owner = me_r.json().get("login", "")

        # 2. Create repo (or use existing)
        create_r = await client.post(
            "https://api.github.com/user/repos",
            headers=headers,
            json={
                "name": safe_name,
                "private": is_private,
                "auto_init": False,
                "description": "Generated by CrucibAI",
            },
        )
        if create_r.status_code not in (201, 422):  # 422 = already exists
            raise HTTPException(
                status_code=502,
                detail=f"GitHub repo creation failed: {create_r.text[:200]}",
            )

        repo_url = f"https://github.com/{owner}/{safe_name}"
        clone_url = f"https://github.com/{owner}/{safe_name}.git"

        # 3. Push files via Contents API
        pushed = []
        skipped = []
        for path, content in files.items():
            safe_path = path.lstrip("/")
            if not safe_path:
                continue
            try:
                raw = content if isinstance(content, bytes) else content.encode("utf-8")
                encoded = base64.b64encode(raw).decode("ascii")
                # Check if file exists (get SHA for update)
                sha = None
                get_r = await client.get(
                    f"https://api.github.com/repos/{owner}/{safe_name}/contents/{safe_path}",
                    headers=headers,
                )
                if get_r.status_code == 200:
                    sha = get_r.json().get("sha")
                payload = {
                    "message": f"feat: add {safe_path} — generated by CrucibAI",
                    "content": encoded,
                }
                if sha:
                    payload["sha"] = sha
                put_r = await client.put(
                    f"https://api.github.com/repos/{owner}/{safe_name}/contents/{safe_path}",
                    headers=headers,
                    json=payload,
                )
                if put_r.status_code in (200, 201):
                    pushed.append(safe_path)
                else:
                    skipped.append({"path": safe_path, "reason": put_r.text[:100]})
            except Exception as e:
                skipped.append({"path": safe_path, "reason": str(e)[:80]})

    # Save to project
    if db and body.project_id:
        await db.projects.update_one(
            {"id": body.project_id, "user_id": user["id"]},
            {"$set": {"github_repo_url": repo_url, "github_clone_url": clone_url}},
        )

    return {
        "repo_url": repo_url,
        "clone_url": clone_url,
        "pushed_files": len(pushed),
        "skipped_files": len(skipped),
        "private": is_private,
    }


@router.get("/git-sync/status")
async def git_sync_status(
    project_id: str = Query(...), user: dict = Depends(_get_auth())
):
    """Return GitHub sync status for a project."""
    db = _get_db()
    if db is None:
        return {"synced": False}
    proj = await db.projects.find_one(
        {"id": project_id, "user_id": user["id"]},
        {"github_repo_url": 1, "github_clone_url": 1},
    )
    if not proj:
        raise HTTPException(status_code=404, detail="Project not found")
    return {
        "synced": bool(proj.get("github_repo_url")),
        "repo_url": proj.get("github_repo_url"),
        "clone_url": proj.get("github_clone_url"),
    }
