"""Public trust routes for benchmark and security posture evidence."""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Iterable

from fastapi import APIRouter, HTTPException

from backend.services.enterprise_readiness import build_enterprise_readiness
from backend.services.proof_manifest import build_replay_plan, verify_manifest
from backend.services.public_proof_readiness import build_public_proof_readiness

logger = logging.getLogger(__name__)


def _first_existing(paths: Iterable[Path]) -> Path | None:
    for path in paths:
        if path.is_file():
            return path
    return None


def _load_json(path: Path) -> dict:
    """Load proof JSON generated by either Python or Windows PowerShell."""
    return json.loads(path.read_text(encoding="utf-8-sig"))


def _load_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def create_trust_router(root_dir: Path) -> APIRouter:
    """Create the public trust router.

    The backend runs from ``backend/`` locally but from ``/app`` in the Docker
    image, so proof lookup checks both repo-relative and image-root locations.
    """
    router = APIRouter(prefix="/api", tags=["trust"])
    proof_candidates = [
        root_dir.parent / "proof" / "benchmarks" / "repeatability_v1",
        root_dir / "proof" / "benchmarks" / "repeatability_v1",
        Path("/proof/benchmarks/repeatability_v1"),
    ]
    full_systems_candidates = [
        root_dir.parent / "proof" / "full_systems",
        root_dir / "proof" / "full_systems",
        Path("/proof/full_systems"),
    ]
    product_dominance_candidates = [
        root_dir.parent / "proof" / "benchmarks" / "product_dominance_v1",
        root_dir / "proof" / "benchmarks" / "product_dominance_v1",
        Path("/proof/benchmarks/product_dominance_v1"),
    ]

    @router.get("/trust/benchmark-summary")
    async def trust_benchmark_summary():
        """Public benchmark summary for trust/status/benchmark pages."""
        summary_path = _first_existing(
            path / "summary.json" for path in proof_candidates
        )
        pass_fail_path = _first_existing(
            path / "PASS_FAIL.md" for path in proof_candidates
        )
        if not summary_path:
            return {
                "status": "not_available",
                "message": "Repeatability benchmark proof has not been generated in this deployment.",
                "prompt_count": 0,
                "passed_count": 0,
                "pass_rate": 0,
                "average_score": 0,
                "proof": {
                    "summary": "proof/benchmarks/repeatability_v1/summary.json",
                    "pass_fail": None,
                },
                "cases": [],
            }
        try:
            data = _load_json(summary_path)
        except Exception as exc:
            logger.warning("trust_benchmark_summary parse failed: %s", exc)
            raise HTTPException(
                status_code=503, detail="Benchmark proof summary unreadable"
            )
        return {
            "status": "ready" if data.get("passed") else "failing",
            "benchmark_version": data.get("benchmark_version"),
            "generated_at": data.get("generated_at"),
            "prompt_count": data.get("prompt_count"),
            "passed_count": data.get("passed_count"),
            "pass_rate": data.get("pass_rate"),
            "average_score": data.get("average_score"),
            "thresholds": data.get("thresholds"),
            "preview_mode": data.get("preview_mode"),
            "summary_sha256": data.get("summary_sha256"),
            "blockers": data.get("blockers") or [],
            "proof": {
                "summary": "proof/benchmarks/repeatability_v1/summary.json",
                "pass_fail": (
                    "proof/benchmarks/repeatability_v1/PASS_FAIL.md"
                    if pass_fail_path
                    else None
                ),
            },
            "cases": [
                {
                    "id": ((case.get("case") or {}).get("id")),
                    "category": ((case.get("case") or {}).get("category")),
                    "score": case.get("score"),
                    "passed": case.get("passed"),
                }
                for case in (data.get("results") or [])
                if isinstance(case, dict)
            ],
        }

    @router.get("/trust/security-posture")
    async def trust_security_posture():
        """Public security posture summary without exposing secret values."""
        return {
            "database": "PostgreSQL only",
            "tenant_isolation": "auth and project ownership enforced on workspace/job/helper routes",
            "terminal_policy": {
                "status": "restricted",
                "public_default": "disabled for non-admin users in production",
                "boundary": "project-scoped with command deny policy, in-memory audit trail, and strict production gate",
                "sandbox_position": "generated-code execution uses the sandbox executor; interactive host terminal remains blocked for broad public exposure",
            },
            "sandbox_policy": {
                "generated_code": "process-level sandbox executor with timeout, output, file-size, memory, CPU, and process limits",
                "interactive_terminal": "disabled for non-admin users in production",
                "container_terminal": "not exposed to public users",
            },
            "community": {
                "templates": "/api/community/templates",
                "case_studies": "/api/community/case-studies",
                "moderation_policy": "/api/community/moderation-policy",
            },
            "proof_locations": [
                "proof/phase2_security/",
                "proof/pipeline_crash_fix/",
                "proof/live_production_golden_path/",
                "proof/benchmarks/",
                "proof/full_systems/",
            ],
            "generated_app_publish": {
                "mode": "in-platform public URL",
                "route": "/published/{job_id}/",
                "external_providers": "Vercel/Netlify/Railway adapters remain separate provider work",
            },
        }

    @router.get("/trust/enterprise-readiness")
    async def trust_enterprise_readiness():
        """Honest enterprise, governance, payment, and cost-control readiness matrix."""
        return build_enterprise_readiness(root_dir)

    @router.get("/trust/public-proof-readiness")
    async def trust_public_proof_readiness():
        """Map public growth claims to proof artifacts, routes, and remaining gaps."""
        return build_public_proof_readiness(root_dir)

    @router.get("/trust/full-systems-summary")
    async def trust_full_systems_summary():
        """Public summary of the latest full systems gate proof."""
        summary_path = _first_existing(
            path / "summary.json" for path in full_systems_candidates
        )
        pass_fail_path = _first_existing(
            path / "PASS_FAIL.md" for path in full_systems_candidates
        )
        if not summary_path:
            return {
                "status": "not_available",
                "message": "Full systems gate proof has not been generated in this deployment.",
                "required_failures": None,
                "gates": [],
                "proof": {
                    "summary": "proof/full_systems/summary.json",
                    "pass_fail": None,
                },
            }
        try:
            data = _load_json(summary_path)
        except Exception as exc:
            logger.warning("trust_full_systems_summary parse failed: %s", exc)
            raise HTTPException(
                status_code=503, detail="Full systems proof summary unreadable"
            )

        results = data.get("results") or []
        gates = []
        if isinstance(results, list):
            for item in results:
                if not isinstance(item, dict):
                    continue
                gates.append(
                    {
                        "name": item.get("name"),
                        "required": bool(item.get("required")),
                        "status": item.get("status"),
                        "duration_seconds": item.get("duration_seconds"),
                    }
                )
        required_failures = data.get("required_failures")
        return {
            "status": "ready" if required_failures == 0 else "failing",
            "generated_at": data.get("generated_at"),
            "base_url": data.get("base_url"),
            "required_failures": required_failures,
            "gates": gates,
            "proof": {
                "summary": "proof/full_systems/summary.json",
                "pass_fail": (
                    "proof/full_systems/PASS_FAIL.md" if pass_fail_path else None
                ),
            },
        }

    @router.get("/trust/summary")
    async def trust_summary():
        """Compact trust summary consumed by app shell surfaces."""
        benchmark = await trust_benchmark_summary()
        security = await trust_security_posture()
        enterprise = await trust_enterprise_readiness()
        full_systems = await trust_full_systems_summary()
        benchmark_ready = benchmark.get("status") == "ready"
        full_systems_ready = full_systems.get("status") == "ready"
        enterprise_ready = enterprise.get("status") == "ready"
        return {
            "status": "ready" if benchmark_ready and full_systems_ready and enterprise_ready else "partial",
            "benchmark": benchmark,
            "security": security,
            "enterprise": enterprise,
            "full_systems": full_systems,
            "checks": {
                "benchmark_ready": benchmark_ready,
                "full_systems_ready": full_systems_ready,
                "enterprise_ready": enterprise_ready,
                "security_posture_ready": True,
            },
        }

    @router.post("/trust/proof-manifest/verify")
    async def trust_proof_manifest_verify(body: dict):
        """Verify signed proof manifest integrity with server-side HMAC secret."""
        secret = (os.environ.get("CRUCIB_PROOF_HMAC_SECRET") or "").strip()
        if not secret:
            raise HTTPException(status_code=503, detail="Proof verification secret not configured")
        manifest = body.get("manifest") if isinstance(body, dict) else None
        if not isinstance(manifest, dict):
            raise HTTPException(status_code=400, detail="manifest object is required")
        return verify_manifest(manifest, secret=secret)

    @router.post("/trust/proof-manifest/replay")
    async def trust_proof_manifest_replay(body: dict):
        """Return deterministic replay plan for a verified proof manifest."""
        secret = (os.environ.get("CRUCIB_PROOF_HMAC_SECRET") or "").strip()
        if not secret:
            raise HTTPException(status_code=503, detail="Proof verification secret not configured")
        manifest = body.get("manifest") if isinstance(body, dict) else None
        if not isinstance(manifest, dict):
            raise HTTPException(status_code=400, detail="manifest object is required")

        verification = verify_manifest(manifest, secret=secret)
        if not verification.get("ok"):
            raise HTTPException(status_code=400, detail={"verification": verification})

        return {
            "verification": verification,
            "replay": build_replay_plan(manifest),
        }

    @router.get("/trust/product-dominance-summary")
    async def trust_product_dominance_summary():
        """Public-facing summary for the signed product dominance benchmark pack."""
        idx_json = _first_existing(
            path / "PUBLIC_PROOF_INDEX.json" for path in product_dominance_candidates
        )
        if not idx_json:
            return {
                "status": "not_available",
                "message": "Product dominance proof has not been generated in this deployment.",
                "canonical_run": None,
                "runs_indexed": 0,
            }

        try:
            payload = _load_json(idx_json)
        except Exception as exc:
            logger.warning("trust_product_dominance_summary parse failed: %s", exc)
            raise HTTPException(status_code=503, detail="Product dominance index unreadable")

        canonical = payload.get("canonical_run") or {}
        run_name = str(canonical.get("run") or "")
        verification_command = None
        if run_name:
            verification_command = (
                "python -c \"import json, pathlib; "
                "from backend.services.proof_manifest import verify_manifest; "
                f"p=pathlib.Path('proof/benchmarks/product_dominance_v1/{run_name}/proof_manifest.json'); "
                "m=json.loads(p.read_text(encoding='utf-8')); "
                "print(verify_manifest(m, secret='local-proof-test-secret'))\""
            )

        return {
            "status": "ready",
            "generated_at": payload.get("generated_at"),
            "canonical_run": canonical,
            "runs_indexed": len(payload.get("runs") or []),
            "signed_runs": len(payload.get("signed_runs") or []),
            "verification": {
                "env_var": "CRUCIB_PROOF_HMAC_SECRET",
                "env_example": "$env:CRUCIB_PROOF_HMAC_SECRET = 'local-proof-test-secret'",
                "command": verification_command,
            },
            "artifacts": {
                "index_markdown": "proof/benchmarks/product_dominance_v1/PUBLIC_PROOF_INDEX.md",
                "index_json": "proof/benchmarks/product_dominance_v1/PUBLIC_PROOF_INDEX.json",
                "landing_html": "proof/benchmarks/product_dominance_v1/PUBLIC_PROOF_LANDING.html",
            },
        }

    @router.get("/trust/product-dominance-index")
    async def trust_product_dominance_index():
        """Return published index artifacts (markdown/html/json) for direct rendering."""
        base = _first_existing(path for path in product_dominance_candidates)
        if not base:
            return {
                "status": "not_available",
                "message": "Product dominance proof directory not found.",
            }

        md_path = base / "PUBLIC_PROOF_INDEX.md"
        html_path = base / "PUBLIC_PROOF_LANDING.html"
        json_path = base / "PUBLIC_PROOF_INDEX.json"

        if not md_path.exists() and not html_path.exists() and not json_path.exists():
            return {
                "status": "not_available",
                "message": "Product dominance public proof artifacts are missing.",
            }

        response = {
            "status": "ready",
            "markdown": _load_text(md_path) if md_path.exists() else None,
            "landing_html": _load_text(html_path) if html_path.exists() else None,
            "index": _load_json(json_path) if json_path.exists() else None,
        }
        return response

    return router


router = create_trust_router(Path(__file__).resolve().parents[1])
