"""Public trust routes for benchmark and security posture evidence."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Iterable

from fastapi import APIRouter, HTTPException

logger = logging.getLogger(__name__)


def _first_existing(paths: Iterable[Path]) -> Path | None:
    for path in paths:
        if path.is_file():
            return path
    return None


def _load_json(path: Path) -> dict:
    """Load proof JSON generated by either Python or Windows PowerShell."""
    return json.loads(path.read_text(encoding="utf-8-sig"))


def create_trust_router(root_dir: Path) -> APIRouter:
    """Create the public trust router.

    The backend runs from ``backend/`` locally but from ``/app`` in the Docker
    image, so proof lookup checks both repo-relative and image-root locations.
    """
    router = APIRouter(prefix="/api", tags=["trust"])
    proof_candidates = [
        root_dir.parent / "proof" / "benchmarks" / "repeatability_v1",
        root_dir / "proof" / "benchmarks" / "repeatability_v1",
        Path("/proof/benchmarks/repeatability_v1"),
    ]
    full_systems_candidates = [
        root_dir.parent / "proof" / "full_systems",
        root_dir / "proof" / "full_systems",
        Path("/proof/full_systems"),
    ]

    @router.get("/trust/benchmark-summary")
    async def trust_benchmark_summary():
        """Public benchmark summary for trust/status/benchmark pages."""
        summary_path = _first_existing(
            path / "summary.json" for path in proof_candidates
        )
        pass_fail_path = _first_existing(
            path / "PASS_FAIL.md" for path in proof_candidates
        )
        if not summary_path:
            return {
                "status": "not_available",
                "message": "Repeatability benchmark proof has not been generated in this deployment.",
                "prompt_count": 0,
                "passed_count": 0,
                "pass_rate": 0,
                "average_score": 0,
                "proof": {
                    "summary": "proof/benchmarks/repeatability_v1/summary.json",
                    "pass_fail": None,
                },
                "cases": [],
            }
        try:
            data = _load_json(summary_path)
        except Exception as exc:
            logger.warning("trust_benchmark_summary parse failed: %s", exc)
            raise HTTPException(
                status_code=503, detail="Benchmark proof summary unreadable"
            )
        return {
            "status": "ready" if data.get("passed") else "failing",
            "benchmark_version": data.get("benchmark_version"),
            "generated_at": data.get("generated_at"),
            "prompt_count": data.get("prompt_count"),
            "passed_count": data.get("passed_count"),
            "pass_rate": data.get("pass_rate"),
            "average_score": data.get("average_score"),
            "thresholds": data.get("thresholds"),
            "preview_mode": data.get("preview_mode"),
            "summary_sha256": data.get("summary_sha256"),
            "blockers": data.get("blockers") or [],
            "proof": {
                "summary": "proof/benchmarks/repeatability_v1/summary.json",
                "pass_fail": (
                    "proof/benchmarks/repeatability_v1/PASS_FAIL.md"
                    if pass_fail_path
                    else None
                ),
            },
            "cases": [
                {
                    "id": ((case.get("case") or {}).get("id")),
                    "category": ((case.get("case") or {}).get("category")),
                    "score": case.get("score"),
                    "passed": case.get("passed"),
                }
                for case in (data.get("results") or [])
                if isinstance(case, dict)
            ],
        }

    @router.get("/trust/security-posture")
    async def trust_security_posture():
        """Public security posture summary without exposing secret values."""
        return {
            "database": "PostgreSQL only",
            "tenant_isolation": "auth and project ownership enforced on workspace/job/helper routes",
            "terminal_policy": {
                "status": "restricted",
                "public_default": "disabled for non-admin users in production",
                "boundary": "project-scoped with command deny policy, in-memory audit trail, and strict production gate",
                "sandbox_position": "generated-code execution uses the sandbox executor; interactive host terminal remains blocked for broad public exposure",
            },
            "sandbox_policy": {
                "generated_code": "process-level sandbox executor with timeout, output, file-size, memory, CPU, and process limits",
                "interactive_terminal": "disabled for non-admin users in production",
                "container_terminal": "not exposed to public users",
            },
            "community": {
                "templates": "/api/community/templates",
                "case_studies": "/api/community/case-studies",
                "moderation_policy": "/api/community/moderation-policy",
            },
            "proof_locations": [
                "proof/phase2_security/",
                "proof/pipeline_crash_fix/",
                "proof/live_production_golden_path/",
                "proof/benchmarks/",
                "proof/full_systems/",
            ],
            "generated_app_publish": {
                "mode": "in-platform public URL",
                "route": "/published/{job_id}/",
                "external_providers": "Vercel/Netlify/Railway adapters remain separate provider work",
            },
        }

    @router.get("/trust/full-systems-summary")
    async def trust_full_systems_summary():
        """Public summary of the latest full systems gate proof."""
        summary_path = _first_existing(
            path / "summary.json" for path in full_systems_candidates
        )
        pass_fail_path = _first_existing(
            path / "PASS_FAIL.md" for path in full_systems_candidates
        )
        if not summary_path:
            return {
                "status": "not_available",
                "message": "Full systems gate proof has not been generated in this deployment.",
                "required_failures": None,
                "gates": [],
                "proof": {
                    "summary": "proof/full_systems/summary.json",
                    "pass_fail": None,
                },
            }
        try:
            data = _load_json(summary_path)
        except Exception as exc:
            logger.warning("trust_full_systems_summary parse failed: %s", exc)
            raise HTTPException(
                status_code=503, detail="Full systems proof summary unreadable"
            )

        results = data.get("results") or []
        gates = []
        if isinstance(results, list):
            for item in results:
                if not isinstance(item, dict):
                    continue
                gates.append(
                    {
                        "name": item.get("name"),
                        "required": bool(item.get("required")),
                        "status": item.get("status"),
                        "duration_seconds": item.get("duration_seconds"),
                    }
                )
        required_failures = data.get("required_failures")
        return {
            "status": "ready" if required_failures == 0 else "failing",
            "generated_at": data.get("generated_at"),
            "base_url": data.get("base_url"),
            "required_failures": required_failures,
            "gates": gates,
            "proof": {
                "summary": "proof/full_systems/summary.json",
                "pass_fail": (
                    "proof/full_systems/PASS_FAIL.md" if pass_fail_path else None
                ),
            },
        }

    return router
