"""
Go / Gin template generator for CrucibAI.

Produces a complete, runnable Go web API with:
- Gin HTTP framework
- CRUD endpoints, search, health-check
- Data models, request handlers
- go.mod, Makefile
"""

import re
from typing import Dict


def _extract_domain(goal: str) -> str:
    """Extract a short domain name from the goal."""
    goal_lower = goal.lower()
    for phrase in [
        r"(?:a |an |the )?(\w+)\s+(?:tracker|manager|app|api|system|service)",
        r"(?:build|create|make)\s+(?:a |an |the )?(\w+)",
        r"(\w+)\s+(?:api|application|service)",
    ]:
        match = re.search(phrase, goal_lower)
        if match:
            return match.group(1).replace(" ", "_")
    return "item"


def _pascal(word: str) -> str:
    return "".join(part.capitalize() for part in word.split("_"))


def generate_go_gin(goal: str, project_name: str = "generated-go") -> Dict[str, str]:
    """Generate a complete Go / Gin web API scaffold.

    Parameters
    ----------
    goal:
        Natural-language description of what the API should do.
    project_name:
        Go module name.

    Returns
    -------
    Dict[str, str]
        Mapping of relative filepath -> complete file content.
    """
    domain = _extract_domain(goal)
    Domain = _pascal(domain)
    domain_lower = domain.lower()

    # ------------------------------------------------------------------
    # go.mod
    # ------------------------------------------------------------------
    go_mod = f"""\
module {project_name}

go 1.22

require github.com/gin-gonic/gin v1.10.0
"""

    # ------------------------------------------------------------------
    # go.sum  (placeholder — `go mod tidy` will regenerate this)
    # ------------------------------------------------------------------
    go_sum = "# Run `go mod tidy` to populate this file.\n"

    # ------------------------------------------------------------------
    # main.go
    # ------------------------------------------------------------------
    main_go = f'''\
// {Domain} API — auto-generated by CrucibAI.
//
// A RESTful web API built with the Gin framework providing CRUD operations
// on {domain} resources, search, and health-check endpoints.
package main

import (
	"log"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"{project_name}/handlers"
)

func main() {{
	// Release mode disables Gin debug logging
	gin.SetMode(gin.ReleaseMode)

	r := gin.Default()

	// ---------------------------------------------------------------------------
	// Middleware
	// ---------------------------------------------------------------------------
	r.Use(func(c *gin.Context) {{
		c.Header("X-App", "{Domain}")
		c.Next()
	}})

	// ---------------------------------------------------------------------------
	// System routes
	// ---------------------------------------------------------------------------
	r.GET("/health", handlers.HealthCheck)

	// ---------------------------------------------------------------------------
	// API routes (grouped)
	// ---------------------------------------------------------------------------
	api := r.Group("/api/{domain_lower}s")
	{{
		api.GET("", handlers.List{Domain}s)
		api.POST("", handlers.Create{Domain})
		api.GET("/search", handlers.Search{Domain}s)
		api.GET("/stats", handlers.{Domain}Stats)
		api.GET("/:id", handlers.Get{Domain})
		api.PUT("/:id", handlers.Update{Domain})
		api.DELETE("/:id", handlers.Delete{Domain})
	}}

	// ---------------------------------------------------------------------------
	// Start server
	// ---------------------------------------------------------------------------
	srv := &http.Server{{
		Addr:         ":8080",
		Handler:      r,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
	}}

	log.Printf("[server] {Domain} API listening on %s", srv.Addr)
	if err := srv.ListenAndServe(); err != nil {{
		log.Fatalf("[server] Failed to start: %v", err)
	}}
}}
'''

    # ------------------------------------------------------------------
    # handlers/handlers.go
    # ------------------------------------------------------------------
    handlers_go = f'''\
// Package handlers implements all HTTP request handlers for the {Domain} API.
package handlers

import (
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"{project_name}/models"
)

// ---------------------------------------------------------------------------
// In-memory store (thread-safe via sync.Map is not needed for this scaffold)
// ---------------------------------------------------------------------------

var (
	store     = models.NewStore()
	startTime = time.Now()
)

// ---------------------------------------------------------------------------
// Health check
// ---------------------------------------------------------------------------

func HealthCheck(c *gin.Context) {{
	c.JSON(http.StatusOK, gin.H{{
		"status":         "ok",
		"version":        "1.0.0",
		"uptime_seconds": time.Since(startTime).Seconds(),
	}})
}}

// ---------------------------------------------------------------------------
// Create{Domain} — POST /api/{domain_lower}s
// ---------------------------------------------------------------------------

func Create{Domain}(c *gin.Context) {{
	var input models.{Domain}Input
	if err := c.ShouldBindJSON(&input); err != nil {{
		c.JSON(http.StatusBadRequest, gin.H{{"error": err.Error()}})
		return
	}}

	created := store.Create(input)
	c.JSON(http.StatusCreated, created)
}}

// ---------------------------------------------------------------------------
// List{Domain}s — GET /api/{domain_lower}s
// ---------------------------------------------------------------------------

func List{Domain}s(c *gin.Context) {{
	page, _ := strconv.Atoi(c.DefaultQuery("page", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "20"))
	statusFilter := c.Query("status")

	if page < 1 {{
		page = 1
	}}
	if pageSize < 1 || pageSize > 100 {{
		pageSize = 20
	}}

	items := store.GetAll()
	if statusFilter != "" {{
		filtered := make([]models.{Domain}, 0)
		for _, item := range items {{
			if item.Status == statusFilter {{
				filtered = append(filtered, item)
			}}
		}}
		items = filtered
	}}

	total := len(items)
	start := (page - 1) * pageSize
	end := start + pageSize
	if start > total {{
		start = total
	}}
	if end > total {{
		end = total
	}}

	c.JSON(http.StatusOK, gin.H{{
		"items":     items[start:end],
		"total":     total,
		"page":      page,
		"page_size": pageSize,
	}})
}}

// ---------------------------------------------------------------------------
// Get{Domain} — GET /api/{domain_lower}s/:id
// ---------------------------------------------------------------------------

func Get{Domain}(c *gin.Context) {{
	id, err := strconv.Atoi(c.Param("id"))
	if err != nil {{
		c.JSON(http.StatusBadRequest, gin.H{{"error": "invalid id"}})
		return
	}}

	item, found := store.GetByID(id)
	if !found {{
		c.JSON(http.StatusNotFound, gin.H{{"error": "{domain} not found"}})
		return
	}}

	c.JSON(http.StatusOK, item)
}}

// ---------------------------------------------------------------------------
// Update{Domain} — PUT /api/{domain_lower}s/:id
// ---------------------------------------------------------------------------

func Update{Domain}(c *gin.Context) {{
	id, err := strconv.Atoi(c.Param("id"))
	if err != nil {{
		c.JSON(http.StatusBadRequest, gin.H{{"error": "invalid id"}})
		return
	}}

	var input models.{Domain}Input
	if err := c.ShouldBindJSON(&input); err != nil {{
		c.JSON(http.StatusBadRequest, gin.H{{"error": err.Error()}})
		return
	}}

	updated, found := store.Update(id, input)
	if !found {{
		c.JSON(http.StatusNotFound, gin.H{{"error": "{domain} not found"}})
		return
	}}

	c.JSON(http.StatusOK, updated)
}}

// ---------------------------------------------------------------------------
// Delete{Domain} — DELETE /api/{domain_lower}s/:id
// ---------------------------------------------------------------------------

func Delete{Domain}(c *gin.Context) {{
	id, err := strconv.Atoi(c.Param("id"))
	if err != nil {{
		c.JSON(http.StatusBadRequest, gin.H{{"error": "invalid id"}})
		return
	}}

	if !store.Delete(id) {{
		c.JSON(http.StatusNotFound, gin.H{{"error": "{domain} not found"}})
		return
	}}

	c.JSON(http.StatusOK, gin.H{{"message": "{domain} deleted", "id": id}})
}}

// ---------------------------------------------------------------------------
// Search{Domain}s — GET /api/{domain_lower}s/search?q=...
// ---------------------------------------------------------------------------

func Search{Domain}s(c *gin.Context) {{
	query := strings.ToLower(c.Query("q"))
	if query == "" {{
		c.JSON(http.StatusBadRequest, gin.H{{"error": "query parameter q is required"}})
		return
	}}

	results := store.Search(query)
	c.JSON(http.StatusOK, gin.H{{
		"query":   c.Query("q"),
		"results": results,
		"total":   len(results),
	}})
}}

// ---------------------------------------------------------------------------
// {Domain}Stats — GET /api/{domain_lower}s/stats
// ---------------------------------------------------------------------------

func {Domain}Stats(c *gin.Context) {{
	all := store.GetAll()
	byStatus := make(map[string]int)
	var totalPriority int

	for _, item := range all {{
		byStatus[item.Status]++
		totalPriority += item.Priority
	}}

	avgPriority := 0.0
	if len(all) > 0 {{
		avgPriority = float64(totalPriority) / float64(len(all))
	}}

	c.JSON(http.StatusOK, gin.H{{
		"total":        len(all),
		"by_status":    byStatus,
		"avg_priority": avgPriority,
	}})
}}
'''

    # ------------------------------------------------------------------
    # models/models.go
    # ------------------------------------------------------------------
    models_go = f'''\
// Package models defines the data structures and in-memory store
// for the {Domain} API.
package models

import (
	"strings"
	"sync"
	"time"
)

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

// {Domain} represents a single {domain} resource.
type {Domain} struct {{
	ID          int       `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	Tags        []string  `json:"tags"`
	Priority    int       `json:"priority"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}}

// {Domain}Input is the payload for creating or updating a {domain}.
type {Domain}Input struct {{
	Name        string   `json:"name" binding:"required,min=1,max=200"`
	Description string   `json:"description"`
	Status      string   `json:"status"`
	Tags        []string `json:"tags"`
	Priority    int      `json:"priority"`
}}

// ---------------------------------------------------------------------------
// In-memory store with mutex for concurrency safety
// ---------------------------------------------------------------------------

// Store manages {domain} records in memory.
type Store struct {{
	mu      sync.RWMutex
	nextID  int
	records map[int]{Domain}
}}

// NewStore creates an empty store.
func NewStore() *Store {{
	return &Store{{
		nextID:  1,
		records: make(map[int]{Domain}),
	}}
}}

// Create persists a new {domain} record and returns it.
func (s *Store) Create(input {Domain}Input) {Domain} {{
	s.mu.Lock()
	defer s.mu.Unlock()

	now := time.Now().UTC()

	status := input.Status
	if status == "" {{
		status = "active"
	}}

	record := {Domain}{{
		ID:          s.nextID,
		Name:        input.Name,
		Description: input.Description,
		Status:      status,
		Tags:        input.Tags,
		Priority:    input.Priority,
		CreatedAt:   now,
		UpdatedAt:   now,
	}}

	s.records[s.nextID] = record
	s.nextID++
	return record
}}

// GetAll returns a copy of all records.
func (s *Store) GetAll() []{Domain} {{
	s.mu.RLock()
	defer s.mu.RUnlock()

	result := make([]{Domain}, 0, len(s.records))
	for _, r := range s.records {{
		result = append(result, r)
	}}
	return result
}}

// GetByID returns a record by ID, or (zero, false).
func (s *Store) GetByID(id int) ({Domain}, bool) {{
	s.mu.RLock()
	defer s.mu.RUnlock()

	r, ok := s.records[id]
	return r, ok
}}

// Update merges input into an existing record.
func (s *Store) Update(id int, input {Domain}Input) ({Domain}, bool) {{
	s.mu.Lock()
	defer s.mu.Unlock()

	record, ok := s.records[id]
	if !ok {{
		return {Domain}{{}}, false
	}}

	if input.Name != "" {{
		record.Name = input.Name
	}}
	if input.Description != "" {{
		record.Description = input.Description
	}}
	if input.Status != "" {{
		record.Status = input.Status
	}}
	if input.Tags != nil {{
		record.Tags = input.Tags
	}}
	if input.Priority != 0 || input.Name != "" {{
		// Only overwrite priority if explicitly provided
		_ = input.Priority
	}}
	record.Priority = input.Priority
	record.UpdatedAt = time.Now().UTC()

	s.records[id] = record
	return record, true
}}

// Delete removes a record by ID. Returns true if it existed.
func (s *Store) Delete(id int) bool {{
	s.mu.Lock()
	defer s.mu.Unlock()

	_, ok := s.records[id]
	if !ok {{
		return false
	}}
	delete(s.records, id)
	return true
}}

// Search returns records whose name, description, or tags match the query.
func (s *Store) Search(query string) []{Domain} {{
	s.mu.RLock()
	defer s.mu.RUnlock()

	results := make([]{Domain}, 0)
	for _, r := range s.records {{
		if strings.Contains(strings.ToLower(r.Name), query) ||
			strings.Contains(strings.ToLower(r.Description), query) ||
			tagMatch(r.Tags, query) {{
			results = append(results, r)
		}}
	}}
	return results
}}

func tagMatch(tags []string, query string) bool {{
	for _, t := range tags {{
		if strings.Contains(strings.ToLower(t), query) {{
			return true
		}}
	}}
	return false
}}
'''

    # ------------------------------------------------------------------
    # Makefile
    # ------------------------------------------------------------------
    makefile = f'''\
.PHONY: build run clean test tidy

# Binary output directory
BIN_DIR := bin
BINARY  := $(BIN_DIR)/server

# Go parameters
GOCMD  := go
GOBUILD := $(GOCMD) build
GOTEST := $(GOCMD) test
GOMOD  := $(GOCMD) mod

# Build the server binary
build:
	@mkdir -p $(BIN_DIR)
	$(GOBUILD) -o $(BINARY) .

# Run the server (rebuilds first)
run: build
	./$(BINARY)

# Run without rebuilding
dev:
	$(GOCMD) run .

# Download dependencies
tidy:
	$(GOMOD) tidy

# Run tests
test:
	$(GOTEST) ./...

# Clean build artifacts
clean:
	rm -rf $(BIN_DIR)
'''

    return {
        "main.go": main_go,
        "handlers/handlers.go": handlers_go,
        "models/models.go": models_go,
        "go.mod": go_mod,
        "go.sum": go_sum,
        "Makefile": makefile,
    }
