"""
Node.js / Express template generator for CrucibAI.

Produces a complete, runnable Express backend with:
- CORS, helmet, JSON body-parser
- 5+ REST endpoints including health-check, search, CRUD
- API-key verification middleware
- In-memory data store
"""

import re
from typing import Dict


def _extract_domain(goal: str) -> str:
    """Extract a short domain name from the goal."""
    goal_lower = goal.lower()
    for phrase in [
        r"(?:a |an |the )?(\w+)\s+(?:tracker|manager|app|api|system|service|platform)",
        r"(?:build|create|make|generate)\s+(?:a |an |the )?(\w+)",
        r"(\w+)\s+(?:api|application|service)",
    ]:
        match = re.search(phrase, goal_lower)
        if match:
            return match.group(1).replace(" ", "_")
    return "item"


def _pascal(word: str) -> str:
    return "".join(part.capitalize() for part in word.split("_"))


def _plural(word: str) -> str:
    if word.endswith("y") and not word.endswith("ay") and not word.endswith("ey"):
        return word[:-1] + "ies"
    if word.endswith("s") or word.endswith("x") or word.endswith("z"):
        return word + "es"
    return word + "s"


def generate_node_express(goal: str, project_name: str = "generated-api") -> Dict[str, str]:
    """Generate a complete Node.js/Express backend scaffold.

    Parameters
    ----------
    goal:
        Natural-language description of what the API should do.
    project_name:
        Used for documentation / headers only.

    Returns
    -------
    Dict[str, str]
        Mapping of relative filepath -> complete file content.
    """
    domain = _extract_domain(goal)
    Domain = _pascal(domain)
    domains = _plural(domain)
    Domains = _pascal(domains)

    # ------------------------------------------------------------------
    # backend/server.js
    # ------------------------------------------------------------------
    server_js = f'''\
/**
 * {Domain} API — auto-generated by CrucibAI.
 *
 * A fully functional Express.js REST API with CRUD, search,
 * health-check, and API-key authentication.
 */

"use strict";

const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const apiRouter = require("./routes/api");

const app = express();
const PORT = process.env.PORT || 3001;

// ---------------------------------------------------------------------------
// Middleware
// ---------------------------------------------------------------------------
app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({{ extended: true }}));

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------
app.use("/api/{domains}", apiRouter);

// ---------------------------------------------------------------------------
// Health check
// ---------------------------------------------------------------------------
const startTime = Date.now();

app.get("/health", (req, res) => {{
    res.json({{
        status: "ok",
        version: "1.0.0",
        uptime_seconds: Math.round((Date.now() - startTime) / 1000),
    }});
}});

// ---------------------------------------------------------------------------
// 404 fallback
// ---------------------------------------------------------------------------
app.use((req, res) => {{
    res.status(404).json({{ error: "Route not found" }});
}});

// ---------------------------------------------------------------------------
// Global error handler
// ---------------------------------------------------------------------------
app.use((err, req, res, _next) => {{
    console.error("[server] Unhandled error:", err);
    res.status(500).json({{ error: "Internal server error" }});
}});

// ---------------------------------------------------------------------------
// Start
// ---------------------------------------------------------------------------
app.listen(PORT, () => {{
    console.log(`[server] {Domain} API listening on http://localhost:${{PORT}}`);
    console.log(`[server] Docs: http://localhost:${{PORT}}/health`);
}});

module.exports = app;
'''

    # ------------------------------------------------------------------
    # backend/routes/api.js
    # ------------------------------------------------------------------
    api_js = f'''\
/**
 * API router for {domains}.
 *
 * Mounts CRUD routes, search, and stats endpoints.
 */

"use strict";

const express = require("express");
const { requireAuth } = require("../middleware/auth");
const store = require("../models");

const router = express.Router();

// ---------------------------------------------------------------------------
// List {domains} (paginated, optional status filter)
// ---------------------------------------------------------------------------
router.get("/", (req, res) => {{
    const page = Math.max(1, parseInt(req.query.page, 10) || 1);
    const pageSize = Math.min(100, Math.max(1, parseInt(req.query.page_size, 10) || 20));
    const statusFilter = req.query.status || null;

    let items = store.getAll();

    if (statusFilter) {{
        items = items.filter((i) => i.status === statusFilter);
    }}

    const total = items.length;
    const start = (page - 1) * pageSize;
    const paginated = items.slice(start, start + pageSize);

    res.json({{ items: paginated, total, page, page_size: pageSize }});
}});

// ---------------------------------------------------------------------------
// Create a new {domain}
// ---------------------------------------------------------------------------
router.post("/", requireAuth, (req, res) => {{
    const {{ name, description, status, tags, priority }} = req.body;

    if (!name || typeof name !== "string" || name.trim().length === 0) {{
        return res.status(400).json({{ error: "name is required and must be a non-empty string" }});
    }}

    const created = store.create({{
        name: name.trim(),
        description: description || null,
        status: status || "active",
        tags: Array.isArray(tags) ? tags : [],
        priority: typeof priority === "number" ? priority : 0,
    }});

    res.status(201).json(created);
}});

// ---------------------------------------------------------------------------
// Get single {domain} by ID
// ---------------------------------------------------------------------------
router.get("/:id", (req, res) => {{
    const item = store.getById(parseInt(req.params.id, 10));
    if (!item) {{
        return res.status(404).json({{ error: "{Domain} not found" }});
    }}
    res.json(item);
}});

// ---------------------------------------------------------------------------
// Update {domain}
// ---------------------------------------------------------------------------
router.put("/:id", requireAuth, (req, res) => {{
    const id = parseInt(req.params.id, 10);
    const existing = store.getById(id);
    if (!existing) {{
        return res.status(404).json({{ error: "{Domain} not found" }});
    }}

    const updated = store.update(id, {{
        name: req.body.name ?? existing.name,
        description: req.body.description ?? existing.description,
        status: req.body.status ?? existing.status,
        tags: req.body.tags ?? existing.tags,
        priority: req.body.priority ?? existing.priority,
    }});

    res.json(updated);
}});

// ---------------------------------------------------------------------------
// Delete {domain}
// ---------------------------------------------------------------------------
router.delete("/:id", requireAuth, (req, res) => {{
    const id = parseInt(req.params.id, 10);
    const deleted = store.remove(id);
    if (!deleted) {{
        return res.status(404).json({{ error: "{Domain} not found" }});
    }}
    res.json({{ message: "{Domain} deleted", id }});
}});

// ---------------------------------------------------------------------------
// Search {domains}
// ---------------------------------------------------------------------------
router.get("/search/q", (req, res) => {{
    const query = (req.query.q || "").trim().toLowerCase();
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 20));

    if (!query) {{
        return res.status(400).json({{ error: "Query parameter q is required" }});
    }}

    const results = store
        .getAll()
        .filter((item) => {{
            return (
                item.name.toLowerCase().includes(query) ||
                (item.description && item.description.toLowerCase().includes(query)) ||
                item.tags.some((t) => t.toLowerCase().includes(query))
            );
        }});

    res.json({{ query: req.query.q, results: results.slice(0, limit), total: results.length }});
}});

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------
router.get("/stats/summary", (req, res) => {{
    const all = store.getAll();
    const byStatus = {{}};
    for (const item of all) {{
        byStatus[item.status] = (byStatus[item.status] || 0) + 1;
    }}
    const avgPriority = all.length > 0
        ? all.reduce((sum, i) => sum + i.priority, 0) / all.length
        : 0;

    res.json({{
        total: all.length,
        by_status: byStatus,
        avg_priority: Math.round(avgPriority * 100) / 100,
    }});
}});

module.exports = router;
'''

    # ------------------------------------------------------------------
    # backend/models/index.js
    # ------------------------------------------------------------------
    models_js = f'''\
/**
 * In-memory data store for {domains}.
 *
 * Provides a simple key-value store with auto-incrementing IDs and
 * timestamps — sufficient for generated scaffolds and rapid prototyping.
 */

"use strict";

let nextId = 1;
const records = new Map();

function now() {{
    return new Date().toISOString();
}}

/**
 * Create a new record and persist it.
 */
function create(data) {{
    const id = nextId++;
    const record = {{
        id,
        name: data.name,
        description: data.description || null,
        status: data.status || "active",
        tags: data.tags || [],
        priority: data.priority || 0,
        created_at: now(),
        updated_at: now(),
    }};
    records.set(id, record);
    return {{ ...record }};
}}

/**
 * Return all records as an array.
 */
function getAll() {{
    return Array.from(records.values()).map((r) => ({{ ...r }}));
}}

/**
 * Return a single record by ID, or null.
 */
function getById(id) {{
    const record = records.get(id);
    return record ? {{ ...record }} : null;
}}

/**
 * Update an existing record (shallow merge) and refresh updated_at.
 */
function update(id, data) {{
    const record = records.get(id);
    if (!record) return null;
    Object.assign(record, data, {{ updated_at: now() }});
    return {{ ...record }};
}}

/**
 * Delete a record by ID. Returns the deleted record or null.
 */
function remove(id) {{
    const record = records.get(id);
    if (!record) return null;
    records.delete(id);
    return {{ ...record }};
}}

/**
 * Return current record count.
 */
function count() {{
    return records.size;
}}

module.exports = {{ create, getAll, getById, update, remove, count }};
'''

    # ------------------------------------------------------------------
    # backend/middleware/auth.js
    # ------------------------------------------------------------------
    auth_js = '''\
/**
 * API-key authentication middleware.
 *
 * Reads the `x-api-key` header and compares it against the
 * CRUCIB_API_KEY environment variable (defaults to "dev-key").
 */

"use strict";

const API_KEY = process.env.CRUCIB_API_KEY || "dev-key";

/**
 * Express middleware that rejects requests without a valid API key.
 * Must be attached AFTER the json/bodyParser middleware so that
 * req.body is already populated.
 */
function requireAuth(req, res, next) {
    const key = req.headers["x-api-key"];
    if (!key || key !== API_KEY) {
        return res.status(401).json({
            error: "Invalid or missing API key. Pass x-api-key header.",
        });
    }
    next();
}

module.exports = { requireAuth };
'''

    # ------------------------------------------------------------------
    # backend/package.json
    # ------------------------------------------------------------------
    package_json = f'''\
{{
  "name": "{project_name}",
  "version": "1.0.0",
  "description": "CrucibAI-generated {Domain} REST API",
  "main": "server.js",
  "scripts": {{
    "start": "node server.js",
    "dev": "node --watch server.js"
  }},
  "dependencies": {{
    "cors": "^2.8.5",
    "express": "^4.21.0",
    "helmet": "^8.0.0"
  }},
  "engines": {{
    "node": ">=18.0.0"
  }},
  "license": "MIT"
}}
'''

    return {
        "backend/server.js": server_js,
        "backend/routes/api.js": api_js,
        "backend/models/index.js": models_js,
        "backend/middleware/auth.js": auth_js,
        "backend/package.json": package_json,
    }
