"""
Python CLI template generator for CrucibAI.

Produces a complete, runnable CLI tool with:
- argparse with 3+ sub-commands
- Data classes, helper utilities
- pyproject.toml with console_scripts entry point
"""

import re
from typing import Dict


def _extract_domain(goal: str) -> str:
    """Extract a short domain name from the goal."""
    goal_lower = goal.lower()
    for phrase in [
        r"(?:a |an |the )?(\w+)\s+(?:tool|cli|manager|tracker|utility)",
        r"(?:build|create|make)\s+(?:a |an |the )?(\w+)",
        r"(\w+)\s+(?:cli|command.line)",
    ]:
        match = re.search(phrase, goal_lower)
        if match:
            return match.group(1).replace(" ", "_")
    return "item"


def _pascal(word: str) -> str:
    return "".join(part.capitalize() for part in word.split("_"))


def generate_python_cli(goal: str, project_name: str = "generated-cli") -> Dict[str, str]:
    """Generate a complete Python CLI tool scaffold.

    Parameters
    ----------
    goal:
        Natural-language description of what the CLI should do.
    project_name:
        Package name used in pyproject.toml.

    Returns
    -------
    Dict[str, str]
        Mapping of relative filepath -> complete file content.
    """
    domain = _extract_domain(goal)
    Domain = _pascal(domain)

    # ------------------------------------------------------------------
    # cli/main.py
    # ------------------------------------------------------------------
    main_py = f'''\
#!/usr/bin/env python3
"""
{Domain} CLI — auto-generated by CrucibAI.

A command-line interface for managing {domain} records from the terminal.

Usage:
    {project_name} list [--status STATUS] [--limit N]
    {project_name} add --name NAME [--description DESC] [--priority N]
    {project_name} show ID
    {project_name} delete ID
    {project_name} stats
"""

from __future__ import annotations

import argparse
import json
import sys

from cli.models import {Domain}Record
from cli.utils import (
    load_store,
    save_store,
    print_table,
    print_record,
    print_success,
    print_error,
)


def cmd_list(args: argparse.Namespace) -> None:
    """List {domain} records with optional filtering."""
    store = load_store()
    records = store.get("records", [])

    if args.status:
        records = [r for r in records if r.get("status") == args.status]

    limit = args.limit or len(records)
    records = records[:limit]

    if not records:
        print("No records found.")
        return

    print_table(records)
    print(f"Showing {{len(records)}} record(s).")


def cmd_add(args: argparse.Namespace) -> None:
    """Create a new {domain} record."""
    record = {Domain}Record(
        name=args.name,
        description=args.description or "",
        priority=args.priority or 0,
        status="active",
    )

    store = load_store()
    records = store.setdefault("records", [])
    records.append(record.to_dict())
    save_store(store)

    print_success(f"Created record: {{record.name}} (id={{record.id}})")


def cmd_show(args: argparse.Namespace) -> None:
    """Display a single record by ID."""
    store = load_store()
    record = next(
        (r for r in store.get("records", []) if r["id"] == args.id),
        None,
    )

    if record is None:
        print_error(f"Record with id={{args.id}} not found.")
        sys.exit(1)

    print_record(record)


def cmd_delete(args: argparse.Namespace) -> None:
    """Delete a record by ID."""
    store = load_store()
    records = store.get("records", [])
    original_len = len(records)

    store["records"] = [r for r in records if r["id"] != args.id]

    if len(store["records"]) == original_len:
        print_error(f"Record with id={{args.id}} not found.")
        sys.exit(1)

    save_store(store)
    print_success(f"Deleted record id={{args.id}}.")


def cmd_stats(args: argparse.Namespace) -> None:
    """Print aggregate statistics."""
    store = load_store()
    records = store.get("records", [])

    total = len(records)
    by_status: dict[str, int] = {{}}
    priorities: list[int] = []

    for r in records:
        s = r.get("status", "unknown")
        by_status[s] = by_status.get(s, 0) + 1
        priorities.append(r.get("priority", 0))

    avg_priority = sum(priorities) / max(len(priorities), 1)

    print(f"Total records: {{total}}")
    print(f"Average priority: {{avg_priority:.1f}}")
    for status, count in sorted(by_status.items()):
        print(f"  {{status}}: {{count}}")


def build_parser() -> argparse.ArgumentParser:
    """Build the argument parser with all sub-commands."""
    parser = argparse.ArgumentParser(
        prog="{project_name}",
        description="{Domain} CLI — manage {domain} records from the terminal.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # list
    p_list = sub.add_parser("list", help="List records")
    p_list.add_argument("--status", default=None, help="Filter by status")
    p_list.add_argument("--limit", type=int, default=None, help="Max results")
    p_list.set_defaults(func=cmd_list)

    # add
    p_add = sub.add_parser("add", help="Create a new record")
    p_add.add_argument("--name", required=True, help="Record name")
    p_add.add_argument("--description", default="", help="Description")
    p_add.add_argument("--priority", type=int, default=0, help="Priority 0-10")
    p_add.set_defaults(func=cmd_add)

    # show
    p_show = sub.add_parser("show", help="Display a single record")
    p_show.add_argument("id", type=int, help="Record ID")
    p_show.set_defaults(func=cmd_show)

    # delete
    p_del = sub.add_parser("delete", help="Delete a record")
    p_del.add_argument("id", type=int, help="Record ID")
    p_del.set_defaults(func=cmd_delete)

    # stats
    p_stats = sub.add_parser("stats", help="Show aggregate statistics")
    p_stats.set_defaults(func=cmd_stats)

    return parser


def main() -> None:
    """Entry point called by the console_scripts wrapper."""
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
'''

    # ------------------------------------------------------------------
    # cli/utils.py
    # ------------------------------------------------------------------
    utils_py = f'''\
"""
Utility helpers for the {Domain} CLI.

Handles JSON store persistence and terminal output formatting.
"""

from __future__ import annotations

import json
import os
import textwrap
from pathlib import Path
from typing import Any

DATA_DIR = Path.home() / ".{project_name}"
DATA_FILE = DATA_DIR / "store.json"


def _ensure_dir() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)


def load_store() -> dict[str, Any]:
    """Load the JSON store from disk (returns empty dict if missing)."""
    _ensure_dir()
    if DATA_FILE.exists():
        return json.loads(DATA_FILE.read_text(encoding="utf-8"))
    return {{}}


def save_store(store: dict[str, Any]) -> None:
    """Persist the JSON store to disk."""
    _ensure_dir()
    DATA_FILE.write_text(
        json.dumps(store, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def print_success(message: str) -> None:
    print(f"\\033[32m✓ {{message}}\\033[0m")


def print_error(message: str) -> None:
    print(f"\\033[31m✗ {{message}}\\033[0m", file=sys.stderr) if "sys" in dir() else print(
        f"\\033[31m✗ {{message}}\\033[0m"
    )


def print_record(record: dict) -> None:
    """Print a single record in a readable key-value format."""
    width = max(len(k) for k in record)
    for key, value in record.items():
        label = key.replace("_", " ").capitalize()
        print(f"  {{label:<{{width}}}} : {{value}}")


def print_table(records: list[dict]) -> None:
    """Print a list of records as a simple aligned table."""
    if not records:
        return

    columns = list(records[0].keys())
    col_widths = {{c: max(len(str(c)), *(len(str(r.get(c, ""))) for r in records)) for c in columns}}
    total_width = sum(col_widths.values()) + 3 * (len(columns) - 1) + 4

    # Header
    header = " | ".join(str(c).ljust(col_widths[c]) for c in columns)
    print(f"  {{header}}")
    print(f"  {{'-' * total_width}}")

    # Rows
    for row in records:
        line = " | ".join(str(row.get(c, "")).ljust(col_widths[c]) for c in columns)
        print(f"  {{line}}")
'''

    # ------------------------------------------------------------------
    # cli/models.py
    # ------------------------------------------------------------------
    models_py = f'''\
"""
Data models for the {Domain} CLI.

Uses plain dataclasses instead of Pydantic to keep the CLI lightweight.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field, asdict
from typing import Optional


_next_id = int(time.time())


def _fresh_id() -> int:
    global _next_id
    _next_id += 1
    return _next_id


@dataclass
class {Domain}Record:
    """A single {domain} record managed by the CLI."""

    name: str
    description: str = ""
    status: str = "active"
    priority: int = 0
    tags: list[str] = field(default_factory=list)
    id: int = field(default_factory=_fresh_id)

    def to_dict(self) -> dict:
        """Serialise to a plain dictionary (for JSON persistence)."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "{Domain}Record":
        """Reconstruct from a dictionary."""
        return cls(**{{k: v for k, v in data.items() if k in cls.__dataclass_fields__}})

    def is_valid(self) -> bool:
        """Basic validation check."""
        if not self.name or len(self.name.strip()) == 0:
            return False
        if self.status not in ("active", "inactive", "archived"):
            return False
        if not 0 <= self.priority <= 10:
            return False
        return True
'''

    # ------------------------------------------------------------------
    # cli/__init__.py
    # ------------------------------------------------------------------
    cli_init = f'''\
"""{Domain} CLI package."""
'''
    # ------------------------------------------------------------------
    # requirements.txt
    # ------------------------------------------------------------------
    requirements_txt = """\
# No external dependencies required — uses stdlib only.
# Add third-party packages below if needed (e.g., requests, rich).
"""

    # ------------------------------------------------------------------
    # pyproject.toml
    # ------------------------------------------------------------------
    pyproject_toml = f'''\
[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "{project_name}"
version = "1.0.0"
description = "{Domain} CLI — generated by CrucibAI"
readme = "README.md"
license = {{text = "MIT"}}
requires-python = ">=3.10"

[project.scripts]
{project_name} = "cli.main:main"

[tool.setuptools.packages.find]
include = ["cli*"]
'''

    return {
        "cli/__init__.py": cli_init,
        "cli/main.py": main_py,
        "cli/utils.py": utils_py,
        "cli/models.py": models_py,
        "requirements.txt": requirements_txt,
        "pyproject.toml": pyproject_toml,
    }
