"""
Rust / Axum template generator for CrucibAI.

Produces a complete, runnable Rust web API with:
- Axum HTTP framework, Tokio async runtime
- CRUD endpoints, search, health-check
- Serde serialisation, proper error handling
- Separate modules for handlers and models
"""

import re
from typing import Dict


def _extract_domain(goal: str) -> str:
    """Extract a short domain name from the goal."""
    goal_lower = goal.lower()
    for phrase in [
        r"(?:a |an |the )?(\w+)\s+(?:tracker|manager|app|api|system|service)",
        r"(?:build|create|make)\s+(?:a |an |the )?(\w+)",
        r"(\w+)\s+(?:api|application|service)",
    ]:
        match = re.search(phrase, goal_lower)
        if match:
            return match.group(1).replace(" ", "_")
    return "item"


def _pascal(word: str) -> str:
    return "".join(part.capitalize() for part in word.split("_"))


def _snake(word: str) -> str:
    return word.lower().replace(" ", "_")


def generate_rust_axum(goal: str, project_name: str = "generated-rust") -> Dict[str, str]:
    """Generate a complete Rust / Axum web API scaffold.

    Parameters
    ----------
    goal:
        Natural-language description of what the API should do.
    project_name:
        Cargo package / crate name.

    Returns
    -------
    Dict[str, str]
        Mapping of relative filepath -> complete file content.
    """
    domain = _extract_domain(goal)
    Domain = _pascal(domain)
    domains = _plural(domain)
    Domains = _pascal(domains)

    def _plural(w):
        if w.endswith("y") and not w.endswith("ay") and not w.endswith("ey"):
            return w[:-1] + "ies"
        return w + "s"

    domains = _plural(domain)
    Domains = _pascal(domains)

    # ------------------------------------------------------------------
    # Cargo.toml
    # ------------------------------------------------------------------
    cargo_toml = f"""\
[package]
name = "{project_name}"
version = "1.0.0"
edition = "2021"
description = "{Domain} API — auto-generated by CrucibAI"

[dependencies]
axum = "0.8"
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
tower-http = {{ version = "0.6", features = ["cors"] }}
chrono = {{ version = "0.4", features = ["serde"] }}
"""

    # ------------------------------------------------------------------
    # src/main.rs
    # ------------------------------------------------------------------
    main_rs = f'''\
//! {Domain} API — auto-generated by CrucibAI.
//!
//! A RESTful web API built with Axum and Tokio providing CRUD operations,
//! search, and health-check endpoints for {domain} resources.

mod handlers;
mod models;

use axum::{
    middleware,
    routing::{get, post, put, delete},
    Router,
};
use tower_http::cors::{Any, CorsLayer};

use crate::handlers::*;

/// Build and return the application router.
fn app() -> Router {{
    let cors = CorsLayer::new()
        .allow_origin(Any)
        .allow_methods(Any)
        .allow_headers(Any);

    Router::new()
        // System
        .route("/health", get(health_check))
        // CRUD
        .route(
            "/api/{domains}",
            get(list_{domain}s).post(create_{domain}),
        )
        .route(
            "/api/{domains}/search",
            get(search_{domain}s),
        )
        .route(
            "/api/{domains}/stats",
            get({domain}_stats),
        )
        .route(
            "/api/{domains}/:{domain}_id",
            get(get_{domain}).put(update_{domain}).delete(delete_{domain}),
        )
        .layer(cors)
}}

#[tokio::main]
async fn main() {{
    let app = app();

    let listener = tokio::net::TcpListener::bind("0.0.0.0:8080")
        .await
        .expect("Failed to bind to 0.0.0.0:8080");

    println!("[server] {Domain} API listening on http://localhost:8080");

    axum::serve(listener, app)
        .await
        .expect("Server error");
}}
'''

    # ------------------------------------------------------------------
    # src/models.rs
    # ------------------------------------------------------------------
    models_rs = f'''\
//! Data models for the {Domain} API.
//!
//! Defines request/response structures and the in-memory store with
//! interior mutability via `std::sync::Mutex`.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::sync::Mutex;

// ---------------------------------------------------------------------------
// Request / response types
// ---------------------------------------------------------------------------

/// Payload for creating or updating a {domain}.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct {Domain}Input {{
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default = "default_status")]
    pub status: String,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub priority: i32,
}}

fn default_status() -> String {{
    "active".to_string()
}}

/// A single {domain} record with server-managed fields.
#[derive(Debug, Clone, Serialize)]
pub struct {Domain} {{
    pub id: i64,
    pub name: String,
    pub description: String,
    pub status: String,
    pub tags: Vec<String>,
    pub priority: i32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}}

/// Paginated list response.
#[derive(Debug, Serialize)]
pub struct {Domain}ListResponse {{
    pub items: Vec<{Domain}>,
    pub total: usize,
    pub page: usize,
    pub page_size: usize,
}}

/// Health-check response.
#[derive(Debug, Serialize)]
pub struct HealthResponse {{
    pub status: String,
    pub version: String,
    pub uptime_seconds: f64,
}}

/// Generic message response.
#[derive(Debug, Serialize)]
pub struct MessageResponse {{
    pub message: String,
    pub id: Option<i64>,
}}

/// Search response.
#[derive(Debug, Serialize)]
pub struct SearchResponse {{
    pub query: String,
    pub results: Vec<{Domain}>,
    pub total: usize,
}}

/// Stats response.
#[derive(Debug, Serialize)]
pub struct StatsResponse {{
    pub total: usize,
    pub by_status: std::collections::HashMap<String, usize>,
    pub avg_priority: f64,
}}

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub struct ApiError {{
    pub status: u16,
    pub message: String,
}}

impl ApiError {{
    pub fn not_found(msg: &str) -> Self {{
        Self {{ status: 404, message: msg.to_string() }}
    }}

    pub fn bad_request(msg: &str) -> Self {{
        Self {{ status: 400, message: msg.to_string() }}
    }}
}}

// ---------------------------------------------------------------------------
// In-memory store
// ---------------------------------------------------------------------------

/// Thread-safe in-memory store for {domain} records.
pub struct Store {{
    next_id: Mutex<i64>,
    records: Mutex<std::collections::HashMap<i64, {Domain}>>,
    start_time: std::time::Instant,
}}

impl Store {{
    /// Create a new empty store.
    pub fn new() -> Self {{
        Self {{
            next_id: Mutex::new(1),
            records: Mutex::new(std::collections::HashMap::new()),
            start_time: std::time::Instant::now(),
        }}
    }}

    /// Generate the next auto-increment ID.
    pub fn next_id(&self) -> i64 {{
        let mut id = self.next_id.lock().unwrap();
        let val = *id;
        *id += 1;
        val
    }}

    /// Create a new record.
    pub fn create(&self, input: {Domain}Input) -> {Domain} {{
        let id = self.next_id();
        let now = Utc::now();
        let record = {Domain} {{
            id,
            name: input.name,
            description: input.description,
            status: input.status,
            tags: input.tags,
            priority: input.priority,
            created_at: now,
            updated_at: now,
        }};
        self.records.lock().unwrap().insert(id, record.clone());
        record
    }}

    /// Get all records as a Vec.
    pub fn get_all(&self) -> Vec<{Domain}> {{
        self.records.lock().unwrap().values().cloned().collect()
    }}

    /// Get a single record by ID.
    pub fn get_by_id(&self, id: i64) -> Option<{Domain}> {{
        self.records.lock().unwrap().get(&id).cloned()
    }}

    /// Update a record by ID.
    pub fn update(&self, id: i64, input: {Domain}Input) -> Option<{Domain}> {{
        let mut records = self.records.lock().unwrap();
        if let Some(record) = records.get_mut(&id) {{
            if !input.name.is_empty() {{
                record.name = input.name;
            }}
            if !input.description.is_empty() {{
                record.description = input.description;
            }}
            if !input.status.is_empty() {{
                record.status = input.status;
            }}
            if !input.tags.is_empty() {{
                record.tags = input.tags;
            }}
            record.priority = input.priority;
            record.updated_at = Utc::now();
            Some(record.clone())
        }} else {{
            None
        }}
    }}

    /// Delete a record by ID. Returns true if it existed.
    pub fn delete(&self, id: i64) -> bool {{
        self.records.lock().unwrap().remove(&id).is_some()
    }}

    /// Search records by query string (matches name, description, tags).
    pub fn search(&self, query: &str) -> Vec<{Domain}> {{
        let q = query.to_lowercase();
        self.records
            .lock()
            .unwrap()
            .values()
            .filter(|r| {{
                r.name.to_lowercase().contains(&q)
                    || r.description.to_lowercase().contains(&q)
                    || r.tags.iter().any(|t| t.to_lowercase().contains(&q))
            }})
            .cloned()
            .collect()
    }}

    /// Get uptime in seconds.
    pub fn uptime_secs(&self) -> f64 {{
        self.start_time.elapsed().as_secs_f64()
    }}
}}

/// Global store instance.
pub static STORE: once_cell::sync::Lazy<Store> = once_cell::sync::Lazy::new(Store::new);
'''

    # ------------------------------------------------------------------
    # src/handlers.rs
    # ------------------------------------------------------------------
    handlers_rs = f'''\
//! HTTP request handlers for the {Domain} API.

use axum::{
    extract::{Path, Query, State},
    http::StatusCode,
    response::IntoResponse,
    Json,
};
use serde::Deserialize;

use crate::models::*;

// ---------------------------------------------------------------------------
// Query parameter structs
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub struct ListParams {{
    pub page: Option<usize>,
    pub page_size: Option<usize>,
    pub status: Option<String>,
}}

#[derive(Debug, Deserialize)]
pub struct SearchParams {{
    pub q: String,
}}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

/// GET /health
pub async fn health_check() -> Json<HealthResponse> {{
    Json(HealthResponse {{
        status: "ok".to_string(),
        version: "1.0.0".to_string(),
        uptime_seconds: STORE.uptime_secs(),
    }})
}}

/// GET /api/{domains}
pub async fn list_{domain}s(
    Query(params): Query<ListParams>,
) -> Json<{Domain}ListResponse> {{
    let page = params.page.unwrap_or(1).max(1);
    let page_size = params.page_size.unwrap_or(20).clamp(1, 100);

    let mut items = STORE.get_all();

    if let Some(ref status_filter) = params.status {{
        items.retain(|r| r.status == *status_filter);
    }}

    let total = items.len();
    let start = (page - 1) * page_size;
    let end = (start + page_size).min(total);
    let paginated = items.into_iter().skip(start).take(end - start).collect();

    Json({Domain}ListResponse {{
        items: paginated,
        total,
        page,
        page_size,
    }})
}}

/// POST /api/{domains}
pub async fn create_{domain}(
    Json(input): Json<{Domain}Input>,
) -> (StatusCode, Json<{Domain}>) {{
    let created = STORE.create(input);
    (StatusCode::CREATED, Json(created))
}}

/// GET /api/{domains}/:{domain}_id
pub async fn get_{domain}(
    Path({domain}_id): Path<i64>,
) -> impl IntoResponse {{
    match STORE.get_by_id({domain}_id) {{
        Some(record) => (StatusCode::OK, Json(record)).into_response(),
        None => (
            StatusCode::NOT_FOUND,
            Json(serde_json::json!({{"error": "{Domain} not found"}})),
        )
            .into_response(),
    }}
}}

/// PUT /api/{domains}/:{domain}_id
pub async fn update_{domain}(
    Path({domain}_id): Path<i64>,
    Json(input): Json<{Domain}Input>,
) -> impl IntoResponse {{
    match STORE.update({domain}_id, input) {{
        Some(record) => (StatusCode::OK, Json(record)).into_response(),
        None => (
            StatusCode::NOT_FOUND,
            Json(serde_json::json!({{"error": "{Domain} not found"}})),
        )
            .into_response(),
    }}
}}

/// DELETE /api/{domains}/:{domain}_id
pub async fn delete_{domain}(
    Path({domain}_id): Path<i64>,
) -> impl IntoResponse {{
    if STORE.delete({domain}_id) {{
        (
            StatusCode::OK,
            Json(MessageResponse {{
                message: "{Domain} deleted".to_string(),
                id: Some({domain}_id),
            }}),
        )
            .into_response()
    }} else {{
        (
            StatusCode::NOT_FOUND,
            Json(serde_json::json!({{"error": "{Domain} not found"}})),
        )
            .into_response()
    }}
}}

/// GET /api/{domains}/search?q=...
pub async fn search_{domain}s(
    Query(params): Query<SearchParams>,
) -> Json<SearchResponse> {{
    let results = STORE.search(&params.q);
    let total = results.len();
    Json(SearchResponse {{
        query: params.q,
        results,
        total,
    }})
}}

/// GET /api/{domains}/stats
pub async fn {domain}_stats() -> Json<StatsResponse> {{
    let all = STORE.get_all();
    let mut by_status = std::collections::HashMap::new();
    let mut total_priority = 0i64;

    for record in &all {{
        *by_status.entry(record.status.clone()).or_insert(0) += 1;
        total_priority += record.priority as i64;
    }}

    let avg_priority = if all.is_empty() {{
        0.0
    }} else {{
        total_priority as f64 / all.len() as f64
    }};

    Json(StatsResponse {{
        total: all.len(),
        by_status,
        avg_priority,
    }})
}}
'''

    # We need to update Cargo.toml to include once_cell
    # Let's update the Cargo.toml to include it

    final_cargo = f"""\
[package]
name = "{project_name}"
version = "1.0.0"
edition = "2021"
description = "{Domain} API — auto-generated by CrucibAI"

[dependencies]
axum = "0.8"
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
tower-http = {{ version = "0.6", features = ["cors"] }}
chrono = {{ version = "0.4", features = ["serde"] }}
once_cell = "1"
"""

    return {
        "Cargo.toml": final_cargo,
        "src/main.rs": main_rs,
        "src/handlers.rs": handlers_rs,
        "src/models.rs": models_rs,
    }
