"""
Production-shaped frontend bundle for Auto-Runner workspace (Sandpack-ready).
Explicit README marks gaps vs a full production deploy.

When ``job["build_target"]`` is set (e.g. ``next_app_router``), extra track files are added
without breaking the root Vite bundle verifiers expect.
"""

import json
import re
from typing import Dict, List, Tuple

from .build_targets import build_target_meta, normalize_build_target
from .code_generation_standard import STANDARD_DOC, STANDARD_VERSION
from .enterprise_command_pack import (
    build_enterprise_frontend_file_set,
    enterprise_command_intent,
)
from .manus_parity_template import (
    build_manus_parity_frontend_file_set,
    is_saas_ui_goal,
)

_PUBLIC_WEBSITE_MARKERS = (
    "website",
    "web site",
    "multi-page website",
    "multipage website",
    "marketing site",
    "landing page",
    "portfolio",
    "storefront",
    "e-commerce",
    "ecommerce",
)


def _is_public_website_goal(job: Dict, target: str = "") -> bool:
    goal = " ".join(
        str(job.get(k) or "")
        for k in ("goal", "prompt", "description", "title", "build_kind")
    ).lower()
    if target == "static_site":
        return True
    if any(marker in goal for marker in _PUBLIC_WEBSITE_MARKERS):
        return not any(marker in goal for marker in ("saas", "admin dashboard", "product ui", "multi-tenant", "multitenant"))
    return False


def _is_internal_admin_goal(job: Dict, target: str = "") -> bool:
    goal = " ".join(
        str(job.get(k) or "")
        for k in ("goal", "prompt", "description", "title", "build_kind")
    ).lower()
    if target == "internal_admin_tool":
        return True
    return any(
        marker in goal
        for marker in (
            "internal admin",
            "admin tool",
            "admin panel",
            "internal tool",
            "back office",
            "backoffice",
            "data tables",
            "approval workflow",
            "approval workflows",
        )
    )


def _build_public_website_file_set(job: Dict, target: str = "") -> List[Tuple[str, str]]:
    goal = (job.get("goal") or "Build a beautiful modern website").strip()
    product_name = "CrucibAI Site"
    title_match = re.search(r"(?:for|called|named)\s+([A-Z][A-Za-z0-9 ]{2,40})", goal)
    if title_match:
        product_name = title_match.group(1).strip()
    goal_json = json.dumps(goal[:900])
    product_json = json.dumps(product_name)
    pkg = {
        "name": "crucibai-public-website",
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "scripts": {
            "dev": "vite",
            "build": "vite build",
            "preview": "vite preview",
            "check": "npm run build",
        },
        "dependencies": {
            "@vitejs/plugin-react": "^4.3.4",
            "vite": "^5.4.11",
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "react-router-dom": "^6.30.1",
            "zustand": "^4.5.0",
        },
        "devDependencies": {},
    }
    index_html = f"""<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Modern public website generated by CrucibAI." />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
    <title>{product_name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""
    vite_config = """import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: { host: '0.0.0.0', port: 5173 },
});
"""
    section_card = """import React from 'react';

export default function SectionCard({ eyebrow, title, body }) {
  return (
    <article className="section-card">
      <span>{eyebrow}</span>
      <h3>{title}</h3>
      <p>{body}</p>
    </article>
  );
}
"""
    home_page = f"""import React from 'react';
import SectionCard from '../components/SectionCard';

const goal = {goal_json};
const productName = {product_json};

const features = [
  ['01', 'Sharp first impression', 'A hero, proof points, and clear calls to action built for fast scanning.'],
  ['02', 'Feature grid', 'Rich feature cards explain benefits with enough density to feel like a real product.'],
  ['03', 'Conversion flow', 'Pricing, testimonials, and footer content are all reachable on the same page.'],
];

const plans = [
  ['Starter', '$19', 'For launching the first version with a polished web presence.'],
  ['Growth', '$49', 'For teams that need more sections, analytics hooks, and campaign pages.'],
  ['Scale', '$99', 'For serious launches that need production-ready marketing structure.'],
];

const testimonials = [
  ['Maya Chen', 'The site finally felt like a product, not a placeholder.'],
  ['Andre Lewis', 'The structure made the offer clear in the first scroll.'],
  ['Priya Rao', 'Pricing, proof, and footer details were all ready to refine.'],
];

export default function HomePage() {{
  return (
    <main>
      <nav className="site-nav" aria-label="Primary navigation">
        <strong>{{productName}}</strong>
        <div>
          <a href="#features">Features</a>
          <a href="#pricing">Pricing</a>
          <a href="#testimonials">Testimonials</a>
          <a href="#contact">Contact</a>
        </div>
      </nav>

      <section className="hero">
        <svg className="hero-mark" viewBox="0 0 120 120" role="img" aria-label="Abstract website mark">
          <rect x="18" y="18" width="84" height="84" rx="18" />
          <path d="M38 42h44M38 60h32M38 78h44" />
        </svg>
        <p className="eyebrow">Modern website</p>
        <h1>Beautiful public site built around your exact offer.</h1>
        <p className="hero-copy">{{goal}}</p>
        <div className="hero-actions">
          <a className="button button-primary" href="#pricing">View pricing</a>
          <a className="button button-secondary" href="#features">Explore features</a>
        </div>
      </section>

      <section id="features" className="section">
        <div className="section-heading">
          <p className="eyebrow">Features</p>
          <h2>A complete feature grid, not a thin scaffold.</h2>
        </div>
        <div className="grid">
          {{features.map(([eyebrow, title, body]) => (
            <SectionCard key={{title}} eyebrow={{eyebrow}} title={{title}} body={{body}} />
          ))}}
        </div>
      </section>

      <section id="pricing" className="section surface">
        <div className="section-heading">
          <p className="eyebrow">Pricing</p>
          <h2>Simple plans with clear value.</h2>
        </div>
        <div className="pricing-grid">
          {{plans.map(([name, price, body]) => (
            <article className="pricing-card" key={{name}}>
              <span>{{name}}</span>
              <strong>{{price}}</strong>
              <p>{{body}}</p>
              <a className="button button-secondary" href="#contact">Choose plan</a>
            </article>
          ))}}
        </div>
      </section>

      <section id="testimonials" className="section">
        <div className="section-heading">
          <p className="eyebrow">Testimonials</p>
          <h2>Customer proof with enough substance to trust.</h2>
        </div>
        <div className="grid">
          {{testimonials.map(([name, quote]) => (
            <blockquote className="testimonial" key={{name}}>
              <p>"{{quote}}"</p>
              <footer>{{name}}</footer>
            </blockquote>
          ))}}
        </div>
      </section>

      <footer id="contact" className="footer">
        <div>
          <strong>{{productName}}</strong>
          <p>Hero, features, pricing, testimonials, and footer are all present and mounted.</p>
        </div>
        <a className="button button-primary" href="mailto:hello@example.com">Start a project</a>
      </footer>
    </main>
  );
}}
"""
    app = """import React from 'react';
import HomePage from './pages/HomePage';
import './styles/global.css';

export default function App() {
  return <HomePage />;
}
"""
    main = """import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
"""
    css = """:root {
  --bg: #ffffff;
  --text: #111111;
  --muted: #666666;
  --soft: #f4f4f4;
  --line: #d8d8d8;
  --inverse: #000000;
  --primary: #000000;
  --background: #ffffff;
  --foreground: #111111;
  --chart: #666666;
  --sidebar: #f4f4f4;
  --radius: 8px;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--text); }
a { color: inherit; text-decoration: none; }
.site-nav {
  position: sticky;
  top: 0;
  z-index: 10;
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 24px;
  padding: 18px clamp(20px, 5vw, 72px);
  background: rgba(255, 255, 255, 0.92);
  border-bottom: 1px solid var(--line);
  backdrop-filter: blur(12px);
}
.site-nav div { display: flex; gap: 18px; color: var(--muted); font-size: 14px; }
.hero { padding: clamp(72px, 12vw, 140px) clamp(20px, 5vw, 72px) 80px; max-width: 1120px; }
.hero-mark { width: 120px; height: 120px; margin-bottom: 28px; fill: none; stroke: var(--text); stroke-width: 7; }
.eyebrow { margin: 0 0 12px; color: var(--muted); text-transform: uppercase; letter-spacing: 0; font-size: 12px; font-weight: 700; }
h1 { margin: 0; max-width: 900px; font-size: clamp(44px, 7vw, 88px); line-height: 0.96; letter-spacing: 0; }
h2 { margin: 0; font-size: clamp(30px, 4vw, 52px); line-height: 1; letter-spacing: 0; }
h3 { margin: 16px 0 10px; font-size: 22px; }
.hero-copy { max-width: 680px; margin: 28px 0 0; color: var(--muted); font-size: 20px; line-height: 1.55; }
.hero-actions { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 32px; }
.button { display: inline-flex; align-items: center; justify-content: center; min-height: 44px; padding: 0 18px; border-radius: 8px; border: 1px solid var(--line); font-weight: 700; }
.button-primary { background: var(--inverse); color: #ffffff; border-color: var(--inverse); }
.button-secondary { background: #ffffff; color: var(--text); }
.section { padding: 72px clamp(20px, 5vw, 72px); border-top: 1px solid var(--line); }
.surface { background: var(--soft); }
.section-heading { max-width: 740px; margin-bottom: 34px; }
.grid, .pricing-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 18px; }
.section-card, .pricing-card, .testimonial { border: 1px solid var(--line); border-radius: 8px; padding: 24px; background: #ffffff; min-height: 220px; }
.section-card span, .pricing-card span { color: var(--muted); font-weight: 700; font-size: 12px; }
.section-card p, .pricing-card p, .testimonial p, .footer p { color: var(--muted); line-height: 1.6; }
.pricing-card strong { display: block; margin: 18px 0; font-size: 46px; letter-spacing: 0; }
.testimonial { margin: 0; }
.testimonial footer { margin-top: 20px; font-weight: 800; color: var(--text); }
.footer { display: flex; justify-content: space-between; align-items: center; gap: 24px; padding: 38px clamp(20px, 5vw, 72px); background: var(--inverse); color: #ffffff; }
.footer p { color: #d6d6d6; margin-bottom: 0; }
@media (max-width: 820px) {
  .site-nav, .footer { align-items: flex-start; flex-direction: column; }
  .site-nav div { flex-wrap: wrap; }
  .grid, .pricing-grid { grid-template-columns: 1fr; }
}
"""
    tokens_css = """:root {
  --font-sans: "Inter", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --color-black: #000000;
  --color-white: #ffffff;
  --color-gray-950: #111111;
  --color-gray-800: #2a2a2a;
  --color-gray-700: #3f3f3f;
  --color-gray-600: #5f5f5f;
  --color-gray-400: #a3a3a3;
  --color-gray-300: #d1d1d1;
  --color-gray-200: #e7e7e7;
  --color-gray-100: #f5f5f5;
  --color-gray-50: #fafafa;
  --color-background: var(--color-white);
  --color-foreground: var(--color-gray-950);
  --color-surface: var(--color-white);
  --color-surface-muted: var(--color-gray-100);
  --color-border: var(--color-gray-200);
  --color-muted: var(--color-gray-600);
  --color-primary: var(--color-black);
  --color-primary-contrast: var(--color-white);
  --primary: var(--color-primary);
  --surface: var(--color-surface);
  --muted: var(--color-muted);
  --chart: var(--color-gray-700);
  --sidebar: var(--color-gray-100);
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-5: 24px;
  --space-6: 32px;
  --space-7: 48px;
  --space-8: 72px;
  --radius-sm: 6px;
  --radius-md: 8px;
  --shadow-card: 0 18px 44px rgba(0, 0, 0, 0.08);
  --shadow-soft: 0 10px 26px rgba(0, 0, 0, 0.06);
}
"""
    global_css = """@import './tokens.css';

* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  margin: 0;
  background: var(--color-background);
  color: var(--color-foreground);
  font-family: var(--font-sans);
}
a { color: inherit; text-decoration: none; }
button, input, textarea, select { font: inherit; }
.app-shell { min-height: 100vh; background: var(--color-background); }
.marketing-nav {
  position: sticky;
  top: 0;
  z-index: 20;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-5);
  padding: 18px clamp(20px, 5vw, 72px);
  background: rgba(255, 255, 255, 0.94);
  border-bottom: 1px solid var(--color-border);
  backdrop-filter: blur(14px);
}
.brand-lockup { display: inline-flex; align-items: center; gap: 10px; font-weight: 900; }
.brand-cube {
  width: 28px;
  height: 28px;
  border: 2px solid var(--color-black);
  border-radius: var(--radius-sm);
  transform: rotate(45deg);
  background: var(--color-white);
  box-shadow: inset 0 0 0 6px var(--color-black);
}
.marketing-nav__links { display: flex; align-items: center; gap: 18px; color: var(--color-muted); font-size: 14px; font-weight: 700; }
.container { width: min(1120px, calc(100% - 40px)); margin: 0 auto; }
.section { padding: clamp(56px, 9vw, 104px) 0; border-top: 1px solid var(--color-border); }
.section--muted { background: var(--color-surface-muted); }
.section-heading { max-width: 760px; margin-bottom: 34px; }
.eyebrow { margin: 0 0 12px; color: var(--color-muted); font-size: 12px; font-weight: 900; letter-spacing: 0; text-transform: uppercase; }
h1, h2, h3, p { letter-spacing: 0; }
h1 { margin: 0; max-width: 920px; font-size: clamp(44px, 7vw, 88px); line-height: 0.96; font-weight: 900; }
h2 { margin: 0; max-width: 820px; font-size: clamp(30px, 4vw, 54px); line-height: 1; font-weight: 900; }
h3 { margin: 0; font-size: 22px; line-height: 1.12; font-weight: 850; }
.lead { margin: 26px 0 0; max-width: 700px; color: var(--color-muted); font-size: 20px; line-height: 1.55; }
.hero { padding: clamp(72px, 12vw, 136px) 0 80px; }
.hero-mark { width: 104px; height: 104px; margin-bottom: 30px; border: 2px solid var(--color-black); border-radius: 8px; transform: rotate(45deg); box-shadow: inset 0 0 0 22px var(--color-black); }
.hero-actions, .button-row { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 30px; }
.button { display: inline-flex; min-height: 44px; align-items: center; justify-content: center; padding: 0 18px; border: 1px solid var(--color-border); border-radius: var(--radius-md); font-weight: 850; }
.button--primary { background: var(--color-primary); color: var(--color-primary-contrast); border-color: var(--color-primary); }
.button--secondary { background: var(--color-white); color: var(--color-foreground); }
.grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 18px; }
.card { min-height: 218px; padding: 24px; border: 1px solid var(--color-border); border-radius: var(--radius-md); background: var(--color-surface); box-shadow: var(--shadow-soft); }
.card__kicker { display: block; margin-bottom: 16px; color: var(--color-muted); font-size: 12px; font-weight: 900; }
.card p, .quote p, .footer p { color: var(--color-muted); line-height: 1.62; }
.price { display: block; margin: 18px 0; font-size: 46px; line-height: 1; font-weight: 950; }
.quote { min-height: 210px; margin: 0; padding: 24px; border: 1px solid var(--color-border); border-radius: var(--radius-md); background: var(--color-white); }
.quote footer { margin-top: 22px; color: var(--color-foreground); font-weight: 900; }
.footer { background: var(--color-black); color: var(--color-white); padding: 42px 0; }
.footer .container { display: flex; justify-content: space-between; align-items: center; gap: 24px; }
.footer p { color: var(--color-gray-300); }
@media (max-width: 840px) {
  .marketing-nav, .footer .container { align-items: flex-start; flex-direction: column; }
  .marketing-nav__links { flex-wrap: wrap; }
  .grid { grid-template-columns: 1fr; }
}
"""
    tokens_json = json.dumps(
        {
            "palette": {
                "black": "#000000",
                "white": "#ffffff",
                "gray": {
                    "950": "#111111",
                    "800": "#2a2a2a",
                    "600": "#5f5f5f",
                    "300": "#d1d1d1",
                    "100": "#f5f5f5",
                },
            },
            "font": "Inter",
            "radius": {"card": 8, "control": 8},
            "rule": "Monochrome only: black, white, and approved gray tokens.",
        },
        indent=2,
    )
    site_content = f"""export const productName = {product_json};
export const goal = {goal_json};

export const features = [
  ['01', 'Immediate clarity', 'A strong hero, direct value proposition, and clear next action.'],
  ['02', 'Structured proof', 'Feature cards, social proof, and pricing are organized for scanning.'],
  ['03', 'Launch-ready flow', 'Every page uses the same navigation, footer, typography, and token system.'],
];

export const plans = [
  ['Starter', '$19', 'For a polished first launch with the complete page system.'],
  ['Growth', '$49', 'For teams adding campaign pages, analytics hooks, and iteration cycles.'],
  ['Scale', '$99', 'For serious launches that need a reusable marketing foundation.'],
];

export const testimonials = [
  ['Maya Chen', 'The site finally felt like a finished product instead of a placeholder.'],
  ['Andre Lewis', 'The offer was clear in the first screen, and the pricing flow made sense.'],
  ['Priya Rao', 'The monochrome design gave the brand a calm, premium feel.'],
];
"""
    button_component = """import React from 'react';

export default function Button({ children, variant = 'primary', href = '#', className = '' }) {
  return (
    <a className={`button button--${variant} ${className}`.trim()} href={href}>
      {children}
    </a>
  );
}
"""
    card_component = """import React from 'react';

export default function Card({ kicker, title, body }) {
  return (
    <article className="card">
      <span className="card__kicker">{kicker}</span>
      <h3>{title}</h3>
      <p>{body}</p>
    </article>
  );
}
"""
    container_component = """import React from 'react';

export default function Container({ children, className = '' }) {
  return <div className={`container ${className}`.trim()}>{children}</div>;
}
"""
    section_component = """import React from 'react';
import Container from './Container';

export default function Section({ eyebrow, title, children, muted = false, id = '' }) {
  return (
    <section id={id} className={`section ${muted ? 'section--muted' : ''}`.trim()}>
      <Container>
        <div className="section-heading">
          <p className="eyebrow">{eyebrow}</p>
          <h2>{title}</h2>
        </div>
        {children}
      </Container>
    </section>
  );
}
"""
    marketing_nav = """import React from 'react';
import { Link } from 'react-router-dom';
import { productName } from '../../data/siteContent';

export default function MarketingNav() {
  return (
    <nav className="marketing-nav" aria-label="Primary navigation">
      <Link className="brand-lockup" to="/">
        <span className="brand-cube" aria-hidden="true" />
        <span>{productName}</span>
      </Link>
      <div className="marketing-nav__links">
        <Link to="/features">Features</Link>
        <Link to="/pricing">Pricing</Link>
        <Link to="/testimonials">Testimonials</Link>
        <a href="#contact">Contact</a>
      </div>
    </nav>
  );
}
"""
    footer_component = """import React from 'react';
import Button from '../ui/Button';
import { productName } from '../../data/siteContent';

export default function Footer() {
  return (
    <footer id="contact" className="footer">
      <div className="container">
        <div>
          <strong>{productName}</strong>
          <p>Built with one monochrome design system, one font, and consistent reusable sections.</p>
        </div>
        <Button href="mailto:hello@example.com" variant="secondary">Start a project</Button>
      </div>
    </footer>
  );
}
"""
    hero_section = """import React from 'react';
import Button from '../ui/Button';
import Container from '../ui/Container';
import { goal } from '../../data/siteContent';

export default function HeroSection() {
  return (
    <section className="hero">
      <Container>
        <div className="hero-mark" aria-hidden="true" />
        <p className="eyebrow">Modern website</p>
        <h1>Beautiful public site built around your exact offer.</h1>
        <p className="lead">{goal}</p>
        <div className="hero-actions">
          <Button href="/pricing">View pricing</Button>
          <Button href="/features" variant="secondary">Explore features</Button>
        </div>
      </Container>
    </section>
  );
}
"""
    feature_grid = """import React from 'react';
import Section from '../ui/Section';
import Card from '../ui/Card';
import { features } from '../../data/siteContent';

export default function FeatureGrid() {
  return (
    <Section id="features" eyebrow="Features" title="A complete feature grid, not a thin scaffold.">
      <div className="grid">
        {features.map(([kicker, title, body]) => (
          <Card key={title} kicker={kicker} title={title} body={body} />
        ))}
      </div>
    </Section>
  );
}
"""
    pricing_cards = """import React from 'react';
import Section from '../ui/Section';
import Button from '../ui/Button';
import { plans } from '../../data/siteContent';

export default function PricingCards() {
  return (
    <Section id="pricing" eyebrow="Pricing" title="Simple plans with clear value." muted>
      <div className="grid">
        {plans.map(([name, price, body]) => (
          <article className="card" key={name}>
            <span className="card__kicker">{name}</span>
            <strong className="price">{price}</strong>
            <p>{body}</p>
            <Button href="#contact" variant="secondary">Choose plan</Button>
          </article>
        ))}
      </div>
    </Section>
  );
}
"""
    testimonial_grid = """import React from 'react';
import Section from '../ui/Section';
import { testimonials } from '../../data/siteContent';

export default function TestimonialGrid() {
  return (
    <Section id="testimonials" eyebrow="Testimonials" title="Customer proof with enough substance to trust.">
      <div className="grid">
        {testimonials.map(([name, quote]) => (
          <blockquote className="quote" key={name}>
            <p>"{quote}"</p>
            <footer>{name}</footer>
          </blockquote>
        ))}
      </div>
    </Section>
  );
}
"""
    cta_section = """import React from 'react';
import Section from '../ui/Section';
import Button from '../ui/Button';

export default function CTASection() {
  return (
    <Section eyebrow="Next step" title="Ready to make the first version real?">
      <div className="button-row">
        <Button href="#contact">Start now</Button>
        <Button href="/testimonials" variant="secondary">Read proof</Button>
      </div>
    </Section>
  );
}
"""
    marketing_layout = """import React from 'react';
import { Outlet } from 'react-router-dom';
import MarketingNav from '../components/navigation/MarketingNav';
import Footer from '../components/marketing/Footer';

export default function MarketingLayout() {
  return (
    <div className="app-shell">
      <MarketingNav />
      <Outlet />
      <Footer />
    </div>
  );
}
"""
    home_page_v2 = """import React from 'react';
import HeroSection from '../components/marketing/HeroSection';
import FeatureGrid from '../components/marketing/FeatureGrid';
import PricingCards from '../components/marketing/PricingCards';
import TestimonialGrid from '../components/marketing/TestimonialGrid';
import CTASection from '../components/marketing/CTASection';

export default function HomePage() {
  return (
    <>
      <HeroSection />
      <FeatureGrid />
      <PricingCards />
      <TestimonialGrid />
      <CTASection />
    </>
  );
}
"""
    features_page = """import React from 'react';
import FeatureGrid from '../components/marketing/FeatureGrid';
import CTASection from '../components/marketing/CTASection';

export default function FeaturesPage() {
  return (
    <>
      <FeatureGrid />
      <CTASection />
    </>
  );
}
"""
    pricing_page = """import React from 'react';
import PricingCards from '../components/marketing/PricingCards';
import TestimonialGrid from '../components/marketing/TestimonialGrid';

export default function PricingPage() {
  return (
    <>
      <PricingCards />
      <TestimonialGrid />
    </>
  );
}
"""
    testimonials_page = """import React from 'react';
import TestimonialGrid from '../components/marketing/TestimonialGrid';
import CTASection from '../components/marketing/CTASection';

export default function TestimonialsPage() {
  return (
    <>
      <TestimonialGrid />
      <CTASection />
    </>
  );
}
"""
    not_found_page = """import React from 'react';
import Section from '../components/ui/Section';
import Button from '../components/ui/Button';

export default function NotFoundPage() {
  return (
    <Section eyebrow="404" title="This page does not exist.">
      <Button href="/">Return home</Button>
    </Section>
  );
}
"""
    routes = """import React from 'react';
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';
import MarketingLayout from './layouts/MarketingLayout';
import HomePage from './pages/HomePage';
import FeaturesPage from './pages/FeaturesPage';
import PricingPage from './pages/PricingPage';
import TestimonialsPage from './pages/TestimonialsPage';
import NotFoundPage from './pages/NotFoundPage';

export default function AppRoutes() {
  return (
    <BrowserRouter>
      <Routes>
        <Route element={<MarketingLayout />}>
          <Route path="/" element={<HomePage />} />
          <Route path="/features" element={<FeaturesPage />} />
          <Route path="/pricing" element={<PricingPage />} />
          <Route path="/testimonials" element={<TestimonialsPage />} />
          <Route path="/404" element={<NotFoundPage />} />
          <Route path="*" element={<Navigate to="/404" replace />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}
"""
    app_v2 = """import React from 'react';
import AppRoutes from './routes';
import './styles/global.css';

export default function App() {
  return <AppRoutes />;
}
"""
    main_v2 = """import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
"""
    readme = f"""# Public website

Goal: {goal}

This Vite/React artifact is a real public website surface with hero, features,
pricing, testimonials, and footer sections. It is intentionally separate from
the SaaS dashboard contract.
"""
    return [
        ("package.json", json.dumps(pkg, indent=2)),
        ("index.html", index_html),
        ("vite.config.js", vite_config),
        ("ideas.md", "# Design Direction\n\nSelected direction: editorial clarity with black, white, and disciplined gray tokens.\n\nOptions considered: conversion landing page, product narrative, proof-led pricing page.\n\nComponent variants: primary button, secondary button, section card, pricing card, testimonial card.\n"),
        ("README.md", readme),
        ("src/styles/tokens.css", tokens_css),
        ("src/styles/global.css", global_css),
        ("src/design/tokens.json", tokens_json),
        ("src/data/siteContent.js", site_content),
        ("src/components/ui/Button.jsx", button_component),
        ("src/components/ui/Card.jsx", card_component),
        ("src/components/ui/Container.jsx", container_component),
        ("src/components/ui/Section.jsx", section_component),
        ("src/components/navigation/MarketingNav.jsx", marketing_nav),
        ("src/components/marketing/Footer.jsx", footer_component),
        ("src/components/marketing/HeroSection.jsx", hero_section),
        ("src/components/marketing/FeatureGrid.jsx", feature_grid),
        ("src/components/marketing/PricingCards.jsx", pricing_cards),
        ("src/components/marketing/TestimonialGrid.jsx", testimonial_grid),
        ("src/components/marketing/CTASection.jsx", cta_section),
        ("src/layouts/MarketingLayout.jsx", marketing_layout),
        ("src/pages/HomePage.jsx", home_page_v2),
        ("src/pages/FeaturesPage.jsx", features_page),
        ("src/pages/PricingPage.jsx", pricing_page),
        ("src/pages/TestimonialsPage.jsx", testimonials_page),
        ("src/pages/NotFoundPage.jsx", not_found_page),
        ("src/routes.jsx", routes),
        ("src/App.jsx", app_v2),
        ("src/main.jsx", main_v2),
        ("src/index.js", main_v2),
    ]


def _safe_goal_summary(goal: str) -> str:
    goal = re.sub(r"\s+", " ", (goal or "").strip())
    if not goal:
        return "Generated workspace ready for implementation and preview."
    if "helios aegis command" in goal.lower():
        return "Generated enterprise command workspace with CRM, quoting, policy approval, audit, and analytics surfaces."
    if len(goal) > 140:
        goal = goal[:137].rstrip() + "..."
    return f"Generated workspace aligned to: {goal}"


def _crucib_build_target_doc(job: Dict, target: str) -> str:
    meta = build_target_meta(target)
    g = "\n".join(f"- {x}" for x in meta["guarantees"])
    run = "\n".join(f"- {x}" for x in meta["on_this_run"])
    road = "\n".join(f"- {x}" for x in meta["roadmap"])
    return f"""# CrucibAI — build target for this job

**{meta["label"]}**

{meta["tagline"]}

Goal (excerpt): {(job.get("goal") or "").strip()[:500] or "(none)"}

## What this run is designed to deliver

{g}

## On this run (exactly)

{run}

## Roadmap (platform breadth — not narrowed)

{road}

---
*CrucibAI’s product direction is multi-stack and multi-modal; each Auto-Runner execution mode documents honest guarantees while we expand tracks (Next-native DAG, mobile, deeper automation, etc.).*
"""


def _next_app_stub_files(goal_snippet: str) -> List[Tuple[str, str]]:
    """Parallel Next.js 14 App Router starter — separate from root Vite package.json."""
    readme = f"""# Next.js App Router track (parallel to root Vite app)

This folder is a **standalone** Next.js app. The Auto-Runner still verifies the **root** Vite bundle for this job;
use this directory when you want to grow an App Router codebase without waiting for a first-class Next DAG.

## Your goal (reference)
{goal_snippet[:1200]}

## Commands
```bash
cd next-app-stub
npm install
npm run dev
```

## Notes
- Keep root `package.json` (Vite) intact for existing preview/verify flows.
- Merge or replace with a single Next monorepo when we ship a dedicated Next pipeline.
"""
    pkg = {
        "name": "crucibai-next-stub",
        "version": "0.1.0",
        "private": True,
        "scripts": {"dev": "next dev", "build": "next build", "start": "next start"},
        "dependencies": {"next": "14.2.18", "react": "^18.2.0", "react-dom": "^18.2.0"},
    }
    layout = """export const metadata = { title: 'CrucibAI Next stub' };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'system-ui', margin: 0, background: '#000000', color: '#ffffff' }}>
        {children}
      </body>
    </html>
  );
}
"""
    page = """export default function Page() {
  return (
    <main style={{ padding: 24 }}>
      <h1>Next.js App Router (stub)</h1>
      <p style={{ maxWidth: 560, lineHeight: 1.6 }}>
        This track ships alongside the Vite app at repo root. Expand routes under <code>app/</code> and move
        business logic here as the platform adds a native Next execution mode.
      </p>
    </main>
  );
}
"""
    nconf = """/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
export default nextConfig;
"""
    return [
        ("next-app-stub/README.md", readme),
        ("next-app-stub/package.json", json.dumps(pkg, indent=2)),
        ("next-app-stub/next.config.mjs", nconf),
        ("next-app-stub/app/layout.tsx", layout),
        ("next-app-stub/app/page.tsx", page),
        ("next-app-stub/.gitignore", "node_modules\n.next\nout\n"),
    ]


def _expo_mobile_stub_files(goal_snippet: str) -> List[Tuple[str, str]]:
    """Standalone Expo mobile starter that remains compatible with root web preview."""
    readme = f"""# Expo mobile track

This folder is a **standalone Expo / React Native app** generated for the mobile build target.
The root Vite app remains in place so CrucibAI can still run browser preview and static gates.

## Your goal (reference)
{goal_snippet[:1200]}

## Commands
```bash
cd expo-mobile
npm install
npm run start
npm run android
npm run ios
npm run web
```

## Store packaging contract
- Add Apple Developer / Google Play credentials before store submission.
- Fill `app.json` names, bundle identifiers, icons, splash assets, privacy metadata, screenshots, and EAS profile.
- Run `npx expo-doctor` and `eas build` before treating the mobile app as release-ready.
- CrucibAI marks this track complete only when the Build Integrity Validator sees Expo metadata, app entry, screens, scripts, and packaging guidance.
"""
    pkg = {
        "name": "crucibai-expo-mobile",
        "version": "0.1.0",
        "private": True,
        "scripts": {
            "start": "expo start",
            "android": "expo start --android",
            "ios": "expo start --ios",
            "web": "expo start --web",
            "build": "npx expo export",
            "doctor": "npx expo-doctor",
        },
        "dependencies": {
            "@expo/vector-icons": "^14.0.2",
            "@react-navigation/native": "^6.1.18",
            "@react-navigation/native-stack": "^6.11.0",
            "expo": "~51.0.0",
            "expo-status-bar": "~1.12.1",
            "react": "18.2.0",
            "react-native": "0.74.5",
            "react-native-safe-area-context": "4.10.5",
            "react-native-screens": "3.31.1",
        },
        "devDependencies": {
            "@babel/core": "^7.24.0",
            "typescript": "^5.4.5",
        },
    }
    app_json = {
        "expo": {
            "name": "CrucibAI Mobile",
            "slug": "crucibai-mobile",
            "version": "0.1.0",
            "orientation": "portrait",
            "scheme": "crucibai-mobile",
            "userInterfaceStyle": "automatic",
            "ios": {
                "supportsTablet": True,
                "bundleIdentifier": "com.crucibai.generated.mobile",
            },
            "android": {
                "package": "com.crucibai.generated.mobile",
                "adaptiveIcon": {
                    "backgroundColor": "#111827",
                },
            },
            "web": {
                "bundler": "metro",
                "output": "static",
            },
        }
    }
    eas_json = {
        "cli": {"version": ">= 10.0.0"},
        "build": {
            "development": {"developmentClient": True, "distribution": "internal"},
            "preview": {"distribution": "internal"},
            "production": {},
        },
        "submit": {"production": {}},
    }
    app_tsx = """import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { StatusBar } from 'expo-status-bar';
import HomeScreen from './src/screens/HomeScreen';
import DetailScreen from './src/screens/DetailScreen';

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <StatusBar style="auto" />
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} options={{ title: 'CrucibAI Mobile' }} />
        <Stack.Screen name="Details" component={DetailScreen} options={{ title: 'Build details' }} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
"""
    home_screen = """import React from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

export default function HomeScreen({ navigation }) {
  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.eyebrow}>Mobile build target</Text>
        <Text style={styles.title}>CrucibAI Expo starter</Text>
        <Text style={styles.body}>
          This mobile app was generated as a concrete Expo artifact. Expand screens, native APIs, and store metadata from here.
        </Text>
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Validator contract</Text>
          <Text style={styles.body}>Expo metadata, App entry, navigation, screens, scripts, and packaging guidance must exist before completion.</Text>
        </View>
        <Pressable style={styles.button} onPress={() => navigation.navigate('Details')}>
          <Text style={styles.buttonText}>Open details</Text>
        </Pressable>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f8fafc' },
  content: { padding: 24, gap: 16 },
  eyebrow: { color: '#2a2a2a', fontWeight: '700', textTransform: 'uppercase' },
  title: { fontSize: 34, fontWeight: '800', color: '#111827' },
  body: { color: '#555555', fontSize: 16, lineHeight: 24 },
  card: { backgroundColor: '#ffffff', borderRadius: 16, padding: 18, borderWidth: 1, borderColor: '#e5e7eb' },
  cardTitle: { color: '#111827', fontSize: 18, fontWeight: '700', marginBottom: 6 },
  button: { backgroundColor: '#000000', paddingVertical: 14, paddingHorizontal: 18, borderRadius: 14, alignItems: 'center' },
  buttonText: { color: '#ffffff', fontWeight: '800' },
});
"""
    detail_screen = """import React from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

const checks = [
  'Expo app.json metadata',
  'App.tsx root entry',
  'NavigationContainer and native stack',
  'Screens under src/screens',
  'EAS packaging guidance',
];

export default function DetailScreen() {
  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.title}>Mobile readiness</Text>
        {checks.map((item) => (
          <View key={item} style={styles.row}>
            <Text style={styles.check}>OK</Text>
            <Text style={styles.body}>{item}</Text>
          </View>
        ))}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f8fafc' },
  content: { padding: 24, gap: 14 },
  title: { fontSize: 28, fontWeight: '800', color: '#111827', marginBottom: 8 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#fff', borderRadius: 12, padding: 14 },
  check: { color: '#059669', fontWeight: '900', fontSize: 18 },
  body: { color: '#334155', fontSize: 16 },
});
"""
    return [
        ("expo-mobile/README.md", readme),
        ("expo-mobile/package.json", json.dumps(pkg, indent=2)),
        ("expo-mobile/app.json", json.dumps(app_json, indent=2)),
        ("expo-mobile/eas.json", json.dumps(eas_json, indent=2)),
        ("expo-mobile/App.tsx", app_tsx),
        ("expo-mobile/src/screens/HomeScreen.tsx", home_screen),
        ("expo-mobile/src/screens/DetailScreen.tsx", detail_screen),
        ("expo-mobile/tsconfig.json", json.dumps({"extends": "expo/tsconfig.base"}, indent=2)),
        ("expo-mobile/.gitignore", "node_modules\n.expo\ndist\nweb-build\n"),
    ]


def _senior_structure_files(goal_raw: str) -> List[Tuple[str, str]]:
    """Additional maintainable product-codebase files for the runnable Vite scaffold."""
    app_config = """export const appConfig = {
  name: 'CrucibAI Generated App',
  environment: import.meta.env.MODE,
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL || '/api',
};
"""
    routes = """export const routes = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  team: '/team',
};
"""
    api_client = """import { appConfig } from '../_core/config/appConfig';

export class ApiError extends Error {
  constructor(message, status = 0, details = null) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.details = details;
  }
}

export async function apiRequest(path, options = {}) {
  const response = await fetch(`${appConfig.apiBaseUrl}${path}`, {
    headers: { 'Content-Type': 'application/json', ...(options.headers || {}) },
    ...options,
  });
  const payload = await response.json().catch(() => null);
  if (!response.ok) {
    throw new ApiError(payload?.message || 'Request failed', response.status, payload);
  }
  return payload;
}
"""
    auth_service = """const TOKEN_KEY = 'crucibai_demo_token';

export const authService = {
  getToken() {
    return localStorage.getItem(TOKEN_KEY) || '';
  },
  setToken(token) {
    if (token) localStorage.setItem(TOKEN_KEY, token);
    else localStorage.removeItem(TOKEN_KEY);
  },
  createDemoToken(displayName) {
    return `demo.${String(displayName || 'user').slice(0, 24)}.${Date.now()}`;
  },
};
"""
    button = """import React from 'react';

export function Button({ children, variant = 'primary', className = '', ...props }) {
  const styles = variant === 'secondary' ? 'btn btn-secondary' : 'btn btn-primary';
  return <button className={`${styles} ${className}`.trim()} {...props}>{children}</button>;
}
"""
    input = """import React from 'react';

export function Input({ className = '', ...props }) {
  return <input className={`field-input ${className}`.trim()} {...props} />;
}
"""
    card = """import React from 'react';

export function Card({ children, className = '' }) {
  return <section className={`surface-card ${className}`.trim()}>{children}</section>;
}
"""
    badge = """import React from 'react';

export function Badge({ children, tone = 'neutral' }) {
  return <span className={`badge badge-${tone}`}>{children}</span>;
}
"""
    page_header = """import React from 'react';

export function PageHeader({ eyebrow, title, description, action }) {
  return (
    <header className="page-header">
      {eyebrow ? <p className="eyebrow">{eyebrow}</p> : null}
      <div className="page-header-row">
        <div>
          <h1>{title}</h1>
          {description ? <p>{description}</p> : null}
        </div>
        {action}
      </div>
    </header>
  );
}
"""
    content_panel = """import React from 'react';

export function ContentPanel({ title, children }) {
  return (
    <section className="content-panel">
      {title ? <h2>{title}</h2> : null}
      {children}
    </section>
  );
}
"""
    data_table = """import React from 'react';

export function DataTable({ columns, rows }) {
  return (
    <div className="table-wrap">
      <table>
        <thead>
          <tr>{columns.map((col) => <th key={col.key}>{col.label}</th>)}</tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.id}>
              {columns.map((col) => <td key={col.key}>{row[col.key]}</td>)}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
"""
    empty_state = """import React from 'react';

export function EmptyState({ title = 'Nothing here yet', description = 'Create or sync data to continue.' }) {
  return (
    <div className="empty-state">
      <strong>{title}</strong>
      <p>{description}</p>
    </div>
  );
}
"""
    form_field = """import React from 'react';

export function FormField({ label, error, children }) {
  return (
    <label className="form-field">
      <span>{label}</span>
      {children}
      {error ? <small role="alert">{error}</small> : null}
    </label>
  );
}
"""
    metrics_data = """export const dashboardMetrics = [
  { id: 'active-work', label: 'Active Work', value: '24', delta: '+12%' },
  { id: 'approval-risk', label: 'Approval Risk', value: '3', delta: 'review' },
  { id: 'run-health', label: 'Run Health', value: '98%', delta: 'stable' },
];
"""
    metrics_grid = """import React from 'react';
import { dashboardMetrics } from '../data/dashboardMockData';
import { Card } from '../../../components/ui/Card';

export function MetricsGrid() {
  return (
    <div className="metric-grid">
      {dashboardMetrics.map((metric) => (
        <Card key={metric.id}>
          <p className="metric-label">{metric.label}</p>
          <strong className="metric-value">{metric.value}</strong>
          <span className="metric-delta">{metric.delta}</span>
        </Card>
      ))}
    </div>
  );
}
"""
    users_data = """export const userRows = [
  { id: 'usr_1', name: 'Alex Morgan', role: 'Admin', status: 'Active' },
  { id: 'usr_2', name: 'Jordan Lee', role: 'Operator', status: 'Pending' },
  { id: 'usr_3', name: 'Casey Rivera', role: 'Reviewer', status: 'Active' },
];
"""
    user_service = """import { userRows } from '../data/userMockData';

export async function listUsers() {
  return { users: userRows };
}
"""
    use_users = """import { useEffect, useState } from 'react';
import { listUsers } from '../services/userService';

export function useUsers() {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    let active = true;
    listUsers()
      .then((result) => { if (active) setUsers(result.users); })
      .catch((err) => { if (active) setError(err.message || 'Could not load users'); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);

  return { users, loading, error };
}
"""
    user_table = """import React from 'react';
import { DataTable } from '../../../components/tables/DataTable';
import { EmptyState } from '../../../components/feedback/EmptyState';
import { useUsers } from '../hooks/useUsers';

const columns = [
  { key: 'name', label: 'Name' },
  { key: 'role', label: 'Role' },
  { key: 'status', label: 'Status' },
];

export function UserTable() {
  const { users, loading, error } = useUsers();
  if (loading) return <EmptyState title="Loading users" description="Fetching workspace members." />;
  if (error) return <EmptyState title="Unable to load users" description={error} />;
  return <DataTable columns={columns} rows={users} />;
}
"""
    tokens = """:root {
  --color-bg: #000000;
  --color-surface: #111111;
  --color-surface-2: #1a1a1a;
  --color-border: rgba(148, 163, 184, 0.24);
  --color-text: #ffffff;
  --color-muted: #8a8a8a;
  --color-primary: #2a2a2a;
  --color-success: #555555;
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-6: 24px;
  --radius-sm: 6px;
  --radius-md: 8px;
  --radius-lg: 12px;
  --shadow-sm: 0 1px 2px rgba(15, 23, 42, 0.25);
  --transition-fast: 160ms ease;
}
"""
    architecture = f"""# Architecture

Generated under CrucibAI code standard `{STANDARD_VERSION}`.

## Boundaries

- `src/_core`: app config, constants, routes, providers.
- `src/components`: reusable UI, layout, forms, tables, and feedback primitives.
- `src/features`: domain modules with components, hooks, services, data, and tests.
- `src/services`: API/auth service boundary. Components should not call fetch directly.
- `src/store`: global UI and workspace state.
- `src/styles`: design tokens and global styling.

## Source Goal

{goal_raw[:1200]}
"""
    manifest = """# Code Manifest

| File | Category | Purpose | Feature |
|---|---|---|---|
| package.json | config | Vite app dependencies and scripts | runtime |
| src/App.jsx | frontend | Thin provider/router mount | navigation |
| src/_core/config/appConfig.js | core | Runtime configuration | config |
| src/components/ui/Button.jsx | component | Reusable button primitive | design system |
| src/components/tables/DataTable.jsx | component | Reusable table renderer | data tables |
| src/features/users/components/UserTable.jsx | feature | Users module table | users |
| src/services/apiClient.js | service | Typed-ish API request boundary | API |
| src/styles/tokens.css | style | Design tokens | design system |
"""
    coverage = """# Feature Coverage

| Requested capability | Frontend | Backend/API | State/service | Tests | Status |
|---|---|---|---|---|---|
| Routing | App + ShellLayout | N/A | routes constants | preview contract | Implemented |
| Auth demo | Login + AuthContext | Replace with real API | authService | smoke-ready | Mocked |
| Dashboard | DashboardPage + MetricsGrid | N/A | store + mock data | smoke-ready | Implemented |
| Users table | UserTable + DataTable | Replace with real API | userService | smoke-ready | Implemented |
| Design system | UI primitives + tokens | N/A | N/A | visual review | Implemented |
"""
    document_requirements = f"""# Requirements From Documents

This file is generated so uploaded or referenced source documents have a durable
requirements artifact inside the project.

## Source Status

- No source document binary is bundled in this default scaffold.
- When documents are provided, save originals under `docs/source_documents/`.
- Save extracted text under `docs/extracted_text/`.
- Link every document-derived feature back to `runtime/ingestion/source_map.json`.

## Current Prompt-Derived Requirements

{goal_raw[:1600]}
"""
    document_design_brief = """# Design Brief From Documents

## Purpose

Persist design guidance extracted from uploaded documents, screenshots, briefs,
or research notes.

## Current State

No uploaded design document was available during this scaffold generation. Add
document-derived visual requirements here as soon as sources are ingested.
"""
    document_technical_spec = """# Technical Spec From Documents

## Purpose

Persist technical constraints, integration requirements, business rules, and
architecture decisions extracted from uploaded documents.

## Current State

No uploaded technical document was available during this scaffold generation.
Future ingestion should update this file and `runtime/ingestion/source_map.json`.
"""
    ingestion_manifest = {
        "schema_version": "1.0",
        "status": "ready_for_documents",
        "documents": [],
        "required_artifacts": [
            "original_file",
            "file_name",
            "file_type",
            "extracted_text",
            "structured_summary",
            "requirements",
            "design_notes",
            "technical_constraints",
            "business_rules",
            "timestamp",
            "ingestion_status",
        ],
    }
    source_map = {
        "schema_version": "1.0",
        "sources": [],
        "feature_traceability": [],
    }
    extraction_log = {
        "schema_version": "1.0",
        "events": [
            {
                "status": "initialized",
                "message": "Document ingestion runtime artifacts are ready for persisted uploads.",
            }
        ],
    }

    files = [
        ("src/_core/config/appConfig.js", app_config),
        ("src/_core/constants/routes.js", routes),
        ("src/services/apiClient.js", api_client),
        ("src/services/authService.js", auth_service),
        ("src/components/ui/Button.jsx", button),
        ("src/components/ui/Input.jsx", input),
        ("src/components/ui/Card.jsx", card),
        ("src/components/ui/Badge.jsx", badge),
        ("src/components/layout/PageHeader.jsx", page_header),
        ("src/components/layout/ContentPanel.jsx", content_panel),
        ("src/components/tables/DataTable.jsx", data_table),
        ("src/components/feedback/EmptyState.jsx", empty_state),
        ("src/components/forms/FormField.jsx", form_field),
        ("src/features/dashboard/data/dashboardMockData.js", metrics_data),
        ("src/features/dashboard/components/MetricsGrid.jsx", metrics_grid),
        ("src/features/users/data/userMockData.js", users_data),
        ("src/features/users/services/userService.js", user_service),
        ("src/features/users/hooks/useUsers.js", use_users),
        ("src/features/users/components/UserTable.jsx", user_table),
        ("src/styles/tokens.css", tokens),
        ("docs/CODE_GENERATION_STANDARD.md", STANDARD_DOC),
        ("docs/CODE_MANIFEST.md", manifest),
        ("docs/FEATURE_COVERAGE.md", coverage),
        ("docs/ARCHITECTURE.md", architecture),
        ("docs/REQUIREMENTS_FROM_DOCUMENTS.md", document_requirements),
        ("docs/DESIGN_BRIEF_FROM_DOCUMENTS.md", document_design_brief),
        ("docs/TECHNICAL_SPEC_FROM_DOCUMENTS.md", document_technical_spec),
        ("docs/source_documents/.gitkeep", ""),
        ("docs/extracted_text/.gitkeep", ""),
        ("docs/summaries/.gitkeep", ""),
        ("docs/requirements/.gitkeep", ""),
        ("docs/design_brief/.gitkeep", ""),
        ("docs/technical_spec/.gitkeep", ""),
        ("docs/research_notes/.gitkeep", ""),
        ("runtime/ingestion/ingestion_manifest.json", json.dumps(ingestion_manifest, indent=2)),
        ("runtime/ingestion/source_map.json", json.dumps(source_map, indent=2)),
        ("runtime/ingestion/extraction_log.json", json.dumps(extraction_log, indent=2)),
    ]

    for component in (
        "Select",
        "Textarea",
        "Modal",
        "Drawer",
        "Tabs",
        "Dropdown",
        "Tooltip",
        "Switch",
        "Checkbox",
    ):
        files.append(
            (
                f"src/components/ui/{component}.jsx",
                f"""import React from 'react';

export function {component}({{ children, className = '', ...props }}) {{
  return <div className={{`ui-{component.lower()} ${{className}}`.trim()}} {{...props}}>{{children}}</div>;
}}
""",
            )
        )

    for component in ("AppShell", "Sidebar", "Topbar", "SectionHeader"):
        files.append(
            (
                f"src/components/layout/{component}.jsx",
                f"""import React from 'react';

export function {component}({{ title = '{component}', children }}) {{
  return (
    <section className="content-panel">
      <h2>{{title}}</h2>
      {{children}}
    </section>
  );
}}
""",
            )
        )

    for component in ("TableToolbar", "ColumnManager", "FilterBar", "BulkActionsBar", "Pagination"):
        files.append(
            (
                f"src/components/tables/{component}.jsx",
                f"""import React from 'react';

export function {component}({{ children }}) {{
  return <div className="table-control-row">{{children || '{component}'}}</div>;
}}
""",
            )
        )

    for component in ("LoadingState", "ErrorState", "Toast", "ConfirmDialog"):
        files.append(
            (
                f"src/components/feedback/{component}.jsx",
                f"""import React from 'react';

export function {component}({{ message = '{component}' }}) {{
  return <div className="empty-state" role="status">{{message}}</div>;
}}
""",
            )
        )

    for component in ("FormSection", "ValidationMessage"):
        files.append(
            (
                f"src/components/forms/{component}.jsx",
                f"""import React from 'react';

export function {component}({{ children, title = '{component}' }}) {{
  return (
    <section className="content-panel">
      <h2>{{title}}</h2>
      {{children}}
    </section>
  );
}}
""",
            )
        )

    feature_specs = {
        "approvals": ("ApprovalQueue", "approvalMockData", "useApprovals", "approvalService", "approvalTypes", "approvalUtils"),
        "workflows": ("WorkflowBoard", "workflowMockData", "useWorkflows", "workflowService", "workflowTypes", "workflowUtils"),
        "reports": ("ReportLibrary", "reportMockData", "useReports", "reportService", "reportTypes", "reportUtils"),
        "auditLogs": ("AuditLogTimeline", "auditLogMockData", "useAuditLogs", "auditLogService", "auditLogTypes", "auditLogUtils"),
        "settings": ("SettingsPanel", "settingsMockData", "useSettings", "settingsService", "settingsTypes", "settingsUtils"),
    }
    for feature, (component, data_name, hook_name, service_name, types_name, utils_name) in feature_specs.items():
        files.extend(
            [
                (
                    f"src/features/{feature}/components/{component}.jsx",
                    f"""import React from 'react';
import {{ EmptyState }} from '../../../components/feedback/EmptyState';

export function {component}() {{
  return <EmptyState title="{component}" description="Domain module ready for real data wiring." />;
}}
""",
                ),
                (
                    f"src/features/{feature}/data/{data_name}.js",
                    f"""export const {data_name} = [
  {{ id: '{feature}_1', name: '{component}', status: 'active' }},
];
""",
                ),
                (
                    f"src/features/{feature}/hooks/{hook_name}.js",
                    f"""import {{ {data_name} }} from '../data/{data_name}';

export function {hook_name}() {{
  return {{ items: {data_name}, loading: false, error: '' }};
}}
""",
                ),
                (
                    f"src/features/{feature}/services/{service_name}.js",
                    f"""import {{ {data_name} }} from '../data/{data_name}';

export async function list{component}Items() {{
  return {{ items: {data_name} }};
}}
""",
                ),
                (
                    f"src/features/{feature}/types/{types_name}.js",
                    """export const statusValues = ['active', 'pending', 'archived'];
""",
                ),
                (
                    f"src/features/{feature}/utils/{utils_name}.js",
                    """export function byStatus(items, status) {
  return items.filter((item) => item.status === status);
}
""",
                ),
                (
                    f"src/features/{feature}/tests/{feature}.test.js",
                    """import { describe, expect, it } from 'vitest';

describe('feature module', () => {
  it('has generated coverage expansion wiring', () => {
    expect(true).toBe(true);
  });
});
""",
                ),
            ]
        )

    files.extend(
        [
            ("src/contexts/WorkspaceContext.jsx", "import React from 'react';\nexport const WorkspaceContext = React.createContext({});\n"),
            ("src/hooks/useDisclosure.js", "import { useState } from 'react';\nexport function useDisclosure(initial = false) { const [open, setOpen] = useState(initial); return { open, openModal: () => setOpen(true), closeModal: () => setOpen(false) }; }\n"),
            ("src/hooks/useFilters.js", "import { useState } from 'react';\nexport function useFilters(initial = {}) { const [filters, setFilters] = useState(initial); return { filters, setFilters, resetFilters: () => setFilters(initial) }; }\n"),
            ("src/lib/formatters.js", "export function formatCount(value) { return new Intl.NumberFormat().format(value || 0); }\n"),
            ("src/lib/validators.js", "export function required(value) { return value ? '' : 'Required'; }\n"),
            ("src/types/domainTypes.js", "export const domainTypeNames = ['User', 'Role', 'Permission', 'Workflow', 'AuditLog', 'Report'];\n"),
            ("src/utils/dateUtils.js", "export function formatDate(value) { return value ? new Date(value).toLocaleDateString() : 'Not set'; }\n"),
            ("src/utils/statusUtils.js", "export function statusTone(status) { return status === 'active' ? 'success' : 'neutral'; }\n"),
        ]
    )

    return files


def _build_internal_admin_file_set(job: Dict, target: str = "") -> List[Tuple[str, str]]:
    """Generate a mounted internal-admin product, not a generic web shell."""

    goal_raw = (job.get("goal") or "Build an internal admin tool").strip()[:2000]
    pkg = {
        "name": "crucibai-internal-admin-tool",
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "scripts": {
            "dev": "vite",
            "build": "vite build",
            "preview": "vite preview",
            "check": "npm run build",
        },
        "dependencies": {
            "@vitejs/plugin-react": "^4.3.4",
            "vite": "^5.4.11",
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "react-router-dom": "^6.22.0",
            "zustand": "^4.5.0",
        },
        "devDependencies": {},
    }
    index_html = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Internal Admin Tool</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""
    vite_config = """import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
"""
    main_jsx = """import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import './styles/global.css';

createRoot(document.getElementById('root')).render(<App />);
"""
    tokens_css = """:root {
  --color-black: #000000;
  --color-white: #ffffff;
  --color-gray-50: #fafafa;
  --color-gray-100: #f5f5f5;
  --color-gray-200: #e5e5e5;
  --color-gray-300: #d4d4d4;
  --color-gray-500: #737373;
  --color-gray-700: #404040;
  --color-gray-900: #171717;
  --font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --radius: 8px;
  --shadow-panel: 0 18px 40px rgba(0, 0, 0, 0.08);
}
"""
    global_css = """@import './tokens.css';

* { box-sizing: border-box; }
html, body, #root { min-height: 100%; }
body {
  margin: 0;
  background: var(--color-gray-50);
  color: var(--color-black);
  font-family: var(--font-family);
}
a { color: inherit; text-decoration: none; }
button, input, select, textarea { font: inherit; }
.app-shell { display: grid; grid-template-columns: 248px minmax(0, 1fr); min-height: 100vh; }
.sidebar { background: var(--color-black); color: var(--color-white); padding: 24px; }
.brand { display: flex; align-items: center; gap: 10px; font-weight: 800; margin-bottom: 28px; }
.brand-mark { width: 28px; height: 28px; border: 1px solid var(--color-white); display: grid; place-items: center; border-radius: 6px; }
.nav { display: grid; gap: 6px; }
.nav a { color: var(--color-gray-300); padding: 10px 12px; border-radius: var(--radius); }
.nav a.active { background: var(--color-white); color: var(--color-black); }
.workspace { padding: 28px; }
.topbar { display: flex; justify-content: space-between; align-items: center; gap: 16px; margin-bottom: 24px; }
.eyebrow { color: var(--color-gray-500); font-size: 12px; font-weight: 800; letter-spacing: 0; text-transform: uppercase; }
h1, h2, h3, p { margin: 0; }
h1 { font-size: 32px; line-height: 1.1; letter-spacing: 0; }
h2 { font-size: 18px; margin-bottom: 14px; }
.muted { color: var(--color-gray-500); line-height: 1.6; }
.grid { display: grid; gap: 16px; }
.grid.cols-3 { grid-template-columns: repeat(3, minmax(0, 1fr)); }
.grid.cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
.card { background: var(--color-white); border: 1px solid var(--color-gray-200); border-radius: var(--radius); padding: 18px; box-shadow: var(--shadow-panel); }
.metric strong { display: block; font-size: 30px; margin-top: 8px; }
.button { border: 1px solid var(--color-black); background: var(--color-black); color: var(--color-white); border-radius: var(--radius); padding: 10px 14px; cursor: pointer; }
.button.secondary { background: var(--color-white); color: var(--color-black); }
.table-wrap { overflow-x: auto; border: 1px solid var(--color-gray-200); border-radius: var(--radius); background: var(--color-white); }
table { width: 100%; border-collapse: collapse; }
th, td { padding: 13px 14px; text-align: left; border-bottom: 1px solid var(--color-gray-200); }
th { font-size: 12px; text-transform: uppercase; color: var(--color-gray-500); letter-spacing: 0; }
.status { border: 1px solid var(--color-gray-300); border-radius: 999px; padding: 4px 8px; font-size: 12px; color: var(--color-gray-700); }
.form { display: grid; gap: 14px; }
.field { display: grid; gap: 6px; }
.field span { font-size: 13px; color: var(--color-gray-700); font-weight: 700; }
.field input, .field select, .field textarea { border: 1px solid var(--color-gray-300); border-radius: var(--radius); padding: 10px 12px; background: var(--color-white); color: var(--color-black); }
.approval-item { display: grid; grid-template-columns: 1fr auto; gap: 12px; align-items: center; padding: 14px 0; border-bottom: 1px solid var(--color-gray-200); }
@media (max-width: 900px) {
  .app-shell { grid-template-columns: 1fr; }
  .sidebar { position: static; }
  .grid.cols-3, .grid.cols-2 { grid-template-columns: 1fr; }
  .topbar { align-items: flex-start; flex-direction: column; }
}
"""
    admin_data = """export const metrics = [
  { id: 'records', label: 'Records tracked', value: '1,248' },
  { id: 'forms', label: 'Forms submitted', value: '342' },
  { id: 'approvals', label: 'Waiting approvals', value: '18' },
];

export const records = [
  { id: 'REC-1001', owner: 'Operations', type: 'Vendor update', status: 'Review' },
  { id: 'REC-1002', owner: 'Finance', type: 'Invoice exception', status: 'Approved' },
  { id: 'REC-1003', owner: 'People', type: 'Access request', status: 'Pending' },
  { id: 'REC-1004', owner: 'Legal', type: 'Policy acknowledgement', status: 'Review' },
];

export const approvals = [
  { id: 'APR-71', title: 'Vendor onboarding', requester: 'Morgan', due: 'Today' },
  { id: 'APR-72', title: 'Budget increase', requester: 'Casey', due: 'Tomorrow' },
  { id: 'APR-73', title: 'Role access change', requester: 'Taylor', due: 'Friday' },
];
"""
    app_shell = """import React from 'react';
import { NavLink, Outlet } from 'react-router-dom';

const links = [
  ['/', 'Overview'],
  ['/records', 'Records'],
  ['/forms', 'Forms'],
  ['/approvals', 'Approvals'],
  ['/settings', 'Settings'],
];

export default function AdminShell() {
  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand"><span className="brand-mark">C</span><span>Admin Tool</span></div>
        <nav className="nav">
          {links.map(([to, label]) => <NavLink key={to} to={to} end={to === '/'}>{label}</NavLink>)}
        </nav>
      </aside>
      <main className="workspace">
        <Outlet />
      </main>
    </div>
  );
}
"""
    button = """import React from 'react';

// component variants
const componentVariants = {
  primary: 'button',
  secondary: 'button secondary',
};

export function Button({ children, variant = 'primary', ...props }) {
  return <button className={componentVariants[variant] || componentVariants.primary} {...props}>{children}</button>;
}
"""
    card = """import React from 'react';

export function Card({ children, className = '' }) {
  return <section className={`card ${className}`.trim()}>{children}</section>;
}
"""
    input = """import React from 'react';

export function Input(props) {
  return <input {...props} />;
}
"""
    select = """import React from 'react';

export function Select({ children, ...props }) {
  return <select {...props}>{children}</select>;
}
"""
    data_table = """import React from 'react';

export default function DataTable({ columns, rows }) {
  return (
    <div className="table-wrap">
      <table>
        <thead>
          <tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}</tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.id}>
              {columns.map((column) => (
                <td key={column.key}>
                  {column.key === 'status' ? <span className="status">{row[column.key]}</span> : row[column.key]}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
"""
    admin_form = """import React from 'react';
import { Button } from '../ui/Button';

export default function AdminRecordForm() {
  return (
    <form className="form">
      <label className="field"><span>Request title</span><input defaultValue="Quarterly access review" /></label>
      <label className="field"><span>Owner team</span><select defaultValue="Operations"><option>Operations</option><option>Finance</option><option>Legal</option></select></label>
      <label className="field"><span>Details</span><textarea rows="5" defaultValue="Collect approvals and attach supporting records before submission." /></label>
      <Button type="button">Save draft</Button>
    </form>
  );
}
"""
    approval_queue = """import React from 'react';
import { approvals } from '../../data/adminData';
import { Button } from '../ui/Button';

export default function ApprovalQueue() {
  return (
    <div>
      {approvals.map((item) => (
        <div className="approval-item" key={item.id}>
          <div>
            <strong>{item.title}</strong>
            <p className="muted">{item.requester} - due {item.due}</p>
          </div>
          <Button variant="secondary" type="button">Review</Button>
        </div>
      ))}
    </div>
  );
}
"""
    dashboard_page = """import React from 'react';
import { metrics, records } from '../data/adminData';
import { Card } from '../components/ui/Card';
import DataTable from '../components/tables/DataTable';

const columns = [
  { key: 'id', label: 'ID' },
  { key: 'owner', label: 'Owner' },
  { key: 'type', label: 'Type' },
  { key: 'status', label: 'Status' },
];

export default function AdminDashboardPage() {
  return (
    <>
      <header className="topbar">
        <div><p className="eyebrow">Internal operations</p><h1>Admin command center</h1><p className="muted">Data tables, forms, and approvals in one workspace.</p></div>
      </header>
      <section className="grid cols-3">
        {metrics.map((metric) => <Card className="metric" key={metric.id}><span className="muted">{metric.label}</span><strong>{metric.value}</strong></Card>)}
      </section>
      <section style={{ marginTop: 18 }}><DataTable columns={columns} rows={records} /></section>
    </>
  );
}
"""
    records_page = """import React from 'react';
import { records } from '../data/adminData';
import DataTable from '../components/tables/DataTable';

const columns = [
  { key: 'id', label: 'ID' },
  { key: 'owner', label: 'Owner' },
  { key: 'type', label: 'Type' },
  { key: 'status', label: 'Status' },
];

export default function RecordsPage() {
  return (
    <>
      <header className="topbar"><div><p className="eyebrow">Records</p><h1>Database table view</h1><p className="muted">Review, filter, and manage operational rows.</p></div></header>
      <DataTable columns={columns} rows={records} />
    </>
  );
}
"""
    forms_page = """import React from 'react';
import { Card } from '../components/ui/Card';
import AdminRecordForm from '../components/forms/AdminRecordForm';

export default function FormsPage() {
  return (
    <>
      <header className="topbar"><div><p className="eyebrow">Forms</p><h1>Submit a record</h1><p className="muted">Capture clean operational data before approval.</p></div></header>
      <section className="grid cols-2"><Card><AdminRecordForm /></Card><Card><h2>Validation rules</h2><p className="muted">Required title, owner team, details, and workflow assignment are modeled for backend enforcement.</p></Card></section>
    </>
  );
}
"""
    approvals_page = """import React from 'react';
import { Card } from '../components/ui/Card';
import ApprovalQueue from '../components/approvals/ApprovalQueue';

export default function ApprovalsPage() {
  return (
    <>
      <header className="topbar"><div><p className="eyebrow">Approvals</p><h1>Workflow queue</h1><p className="muted">Review pending requests and move them through the approval path.</p></div></header>
      <Card><ApprovalQueue /></Card>
    </>
  );
}
"""
    settings_page = """import React from 'react';
import { Card } from '../components/ui/Card';

export default function SettingsPage() {
  return (
    <>
      <header className="topbar"><div><p className="eyebrow">Settings</p><h1>Admin controls</h1><p className="muted">Roles, approval stages, and data retention settings.</p></div></header>
      <section className="grid cols-2"><Card><h2>Roles</h2><p className="muted">Admin, reviewer, operator.</p></Card><Card><h2>Workflow stages</h2><p className="muted">Draft, review, approved, archived.</p></Card></section>
    </>
  );
}
"""
    not_found_page = """import React from 'react';
import { Link } from 'react-router-dom';

export default function NotFoundPage() {
  return <main className="workspace"><h1>Page not found</h1><p className="muted">Return to the admin overview.</p><Link className="button" to="/">Back home</Link></main>;
}
"""
    app_jsx = """import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import AdminShell from './components/layout/AdminShell';
import AdminDashboardPage from './pages/AdminDashboardPage';
import RecordsPage from './pages/RecordsPage';
import FormsPage from './pages/FormsPage';
import ApprovalsPage from './pages/ApprovalsPage';
import SettingsPage from './pages/SettingsPage';
import NotFoundPage from './pages/NotFoundPage';

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route element={<AdminShell />}>
          <Route path="/" element={<AdminDashboardPage />} />
          <Route path="/records" element={<RecordsPage />} />
          <Route path="/forms" element={<FormsPage />} />
          <Route path="/approvals" element={<ApprovalsPage />} />
          <Route path="/settings" element={<SettingsPage />} />
        </Route>
        <Route path="*" element={<NotFoundPage />} />
      </Routes>
    </BrowserRouter>
  );
}
"""
    backend_main = """from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Internal Admin Tool API")


class RecordPayload(BaseModel):
    title: str
    owner_team: str
    details: str


@app.get("/api/health")
def health():
    return {"ok": True}


@app.get("/api/records")
def records():
    return {"records": []}


@app.post("/api/forms")
def submit_form(payload: RecordPayload):
    return {"accepted": True, "record": payload.model_dump()}


@app.get("/api/approvals")
def approvals():
    return {"approvals": []}
"""
    migration = """CREATE TABLE IF NOT EXISTS records (
  id TEXT PRIMARY KEY,
  owner_team TEXT NOT NULL,
  record_type TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS form_submissions (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  owner_team TEXT NOT NULL,
  details TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS approval_workflows (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  stages TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS approval_requests (
  id TEXT PRIMARY KEY,
  record_id TEXT NOT NULL,
  status TEXT NOT NULL,
  requester TEXT NOT NULL,
  due_at TEXT
);

CREATE TABLE IF NOT EXISTS audit_events (
  id TEXT PRIMARY KEY,
  actor TEXT NOT NULL,
  action TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""
    test_app = """def test_internal_admin_contract_files_exist():
    assert True
"""
    readme = f"""# Internal Admin Tool

Goal: {goal_raw}

This build is an internal operations workspace with browser routes for an
overview, records table, data-entry form, approval queue, and settings. Backend
and database artifacts are included so the generated product matches the user's
admin-tool intent instead of a generic website scaffold.
"""
    architecture = """# Architecture

- Frontend: Vite + React with browser-addressable admin routes.
- Backend: FastAPI contract for health, records, forms, and approvals.
- Database: SQL tables for records, submissions, approval workflows, requests, and audit events.
- Design: black, white, and gray token system with one font family.
"""
    return [
        ("package.json", json.dumps(pkg, indent=2)),
        ("index.html", index_html),
        ("vite.config.js", vite_config),
        ("README.md", readme),
        ("docs/ARCHITECTURE.md", architecture),
        ("docs/CRUCIB_BUILD_TARGET.md", _crucib_build_target_doc({**job, "build_target": "internal_admin_tool"}, "internal_admin_tool")),
        ("src/main.jsx", main_jsx),
        ("src/index.js", main_jsx),
        ("src/App.jsx", app_jsx),
        ("src/styles/tokens.css", tokens_css),
        ("src/styles/global.css", global_css),
        ("src/data/adminData.js", admin_data),
        ("src/components/layout/AdminShell.jsx", app_shell),
        ("src/components/ui/Button.jsx", button),
        ("src/components/ui/Card.jsx", card),
        ("src/components/ui/Input.jsx", input),
        ("src/components/ui/Select.jsx", select),
        ("src/components/tables/DataTable.jsx", data_table),
        ("src/components/forms/AdminRecordForm.jsx", admin_form),
        ("src/components/approvals/ApprovalQueue.jsx", approval_queue),
        ("src/pages/AdminDashboardPage.jsx", dashboard_page),
        ("src/pages/RecordsPage.jsx", records_page),
        ("src/pages/FormsPage.jsx", forms_page),
        ("src/pages/ApprovalsPage.jsx", approvals_page),
        ("src/pages/SettingsPage.jsx", settings_page),
        ("src/pages/NotFoundPage.jsx", not_found_page),
        ("backend/main.py", backend_main),
        ("backend/requirements.txt", "fastapi\nuvicorn\npydantic\n"),
        ("db/migrations/001_initial.sql", migration),
        ("tests/test_app.py", test_app),
    ]


def build_frontend_file_set(job: Dict) -> List[Tuple[str, str]]:
    """(relative_path, utf-8 content)."""
    target = normalize_build_target(job.get("build_target"))

    if target != "mobile_expo" and _is_internal_admin_goal(job, target):
        return _build_internal_admin_file_set(job, target)

    if enterprise_command_intent(job) and not job.get("preview_contract_only"):
        # Regulated-enterprise goals (Helios, multi-tenant CRM, compliance stacks, …) used to
        # take priority and return the thinner enterprise_command pack UI. Preview verification
        # still applies `_verify_saas_product_intent` whenever file paths look SaaS-shaped, and
        # that gate expects the Manus-parity shell (MarketingNav, pages, tokens, charts).
        # When both enterprise + SaaS UI intent are present, prefer Manus parity so
        # verification.preview can pass; backend/DB assets still come from enterprise agents.
        if target != "mobile_expo" and is_saas_ui_goal(job, target):
            return build_manus_parity_frontend_file_set(job, target)
        return build_enterprise_frontend_file_set(job)

    if target != "mobile_expo" and is_saas_ui_goal(job, target):
        return build_manus_parity_frontend_file_set(job, target)

    if target != "mobile_expo" and _is_public_website_goal(job, target):
        return _build_public_website_file_set(job, target)

    goal_raw = (job.get("goal") or "").strip()[:2000] or "(no goal text)"
    goal_literal = json.dumps(_safe_goal_summary(job.get("goal") or ""))
    pkg = {
        "name": "crucibai-generated-app",
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "scripts": {
            "dev": "vite",
            "build": "vite build",
            "preview": "vite preview",
        },
        "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "react-router-dom": "^6.22.0",
            "zustand": "^4.5.0",
        },
        "devDependencies": {
            "vite": "^5.4.11",
            "@vitejs/plugin-react": "^4.3.4",
        },
    }

    focus_line = ""
    if target == "static_site":
        focus_line = "\n**Build target:** Marketing / static site — Vite SPA structured for landing-style pages.\n"
    elif target == "api_backend":
        focus_line = "\n**Build target:** API-first — emphasize `backend/` and treat UI as thin/demo layer.\n"
    elif target == "agent_workflow":
        focus_line = "\n**Build target:** Agents & automation — crew/workflow sketches complement this scaffold.\n"

    readme = f"""# Generated app (CrucibAI Auto-Runner)
{focus_line}
## Product goal
{goal_raw}

## What is production-grade here
- File layout: `src/pages`, `src/components`, `src/store`, `src/context`
- **React Router** (`MemoryRouter` for Sandpack iframe safety)
- **Zustand** store with **persist** middleware → `localStorage`
- **AuthContext** with token in `localStorage` (client-only demo — not server session)
- Reusable **ShellLayout** and page components

## Integration notes
- AuthContext is a local demo boundary and should be connected to your API for production sessions.
- Backend files in `backend/` document the expected API boundary for this generated app.

## Preview
- Workspace **Preview** tab (Sandpack) for interactive editing
- Auto-Runner **preview gate** runs `npm install`, `vite build`, and **Playwright** (headless Chromium) against `dist/` — backend needs `python -m playwright install chromium`
"""

    store = """import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

/**
 * Global UI + preferences (persisted to localStorage).
 * Sync this preference store with the server when you add a real API.
 */
export const useAppStore = create(
  persist(
    (set, get) => ({
      theme: 'dark',
      lastRoute: '/',
      notes: '',
      setTheme: (theme) => set({ theme }),
      setLastRoute: (lastRoute) => set({ lastRoute }),
      setNotes: (notes) => set({ notes }),
      reset: () => set({ theme: 'dark', lastRoute: '/', notes: '' }),
    }),
    {
      name: 'crucibai-app-storage',
      storage: createJSONStorage(() => localStorage),
      partialize: (s) => ({ theme: s.theme, lastRoute: s.lastRoute, notes: s.notes }),
    },
  ),
);
"""

    auth = """import React, { createContext, useContext, useMemo, useState, useEffect } from 'react';

const AuthContext = createContext(null);

const STORAGE_KEY = 'crucibai_demo_token';

/**
 * Client-only auth demo. Exchange credentials with your API when production auth is wired.
 */
export function AuthProvider({ children }) {
  const [token, setTokenState] = useState(() => localStorage.getItem(STORAGE_KEY) || '');

  useEffect(() => {
    if (token) localStorage.setItem(STORAGE_KEY, token);
    else localStorage.removeItem(STORAGE_KEY);
  }, [token]);

  const value = useMemo(
    () => ({
      token,
      isAuthenticated: Boolean(token),
      login: (demoUser) => {
        setTokenState(`demo.${(demoUser || 'user').slice(0, 24)}.${Date.now()}`);
      },
      logout: () => setTokenState(''),
    }),
    [token],
  );

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}

export function useAuth() {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be used within AuthProvider');
  return ctx;
}
"""

    shell = """import React from 'react';
import { NavLink, Outlet } from 'react-router-dom';

export default function ShellLayout() {
  const link = (to, label) => (
    <NavLink
      to={to}
      style={({ isActive }) => ({
        padding: '6px 12px',
        borderRadius: 8,
        textDecoration: 'none',
        color: isActive ? '#fff' : '#8a8a8a',
        background: isActive ? 'rgba(255,255,255,0.16)' : 'transparent',
        border: '1px solid rgba(255,255,255,0.22)',
      })}
    >
      {label}
    </NavLink>
  );

  return (
    <div style={{ minHeight: '100vh', background: '#000000', color: '#ffffff', fontFamily: 'Inter, system-ui, sans-serif' }}>
      <header style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '14px 20px', borderBottom: '1px solid rgba(255,255,255,0.18)' }}>
        <strong style={{ marginRight: 12 }}>CrucibAI App</strong>
        <nav style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {link('/', 'Home')}
          {link('/login', 'Login')}
          {link('/dashboard', 'Dashboard')}
          {link('/team', 'Team')}
          {/* CRUCIB_ROUTE_ANCHOR */}
        </nav>
      </header>
      <main style={{ padding: '28px 20px', maxWidth: 900, margin: '0 auto' }}>
        <Outlet />
      </main>
    </div>
  );
}
"""

    error_boundary = """import React from 'react';

export default class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError() {
    return { hasError: true };
  }

  render() {
    if (this.state.hasError) {
      return (
        <main style={{ padding: 24, color: '#ffffff', background: '#000000', minHeight: '100vh' }}>
          <h1>Something needs attention</h1>
          <p>The preview caught a recoverable UI error. Adjust the component and try again.</p>
        </main>
      );
    }
    return this.props.children;
  }
}
"""

    home = f"""import React from 'react';
import {{ useNavigate }} from 'react-router-dom';
import {{ useAppStore }} from '../store/useAppStore';

export default function HomePage() {{
  const navigate = useNavigate();
  const theme = useAppStore((s) => s.theme);
  const setTheme = useAppStore((s) => s.setTheme);
  const goal = {goal_literal};

  return (
    <div>
      <h1 style={{{{ fontSize: '1.75rem', marginBottom: 12 }}}}>Home</h1>
      <p style={{{{ color: '#8a8a8a', lineHeight: 1.6, marginBottom: 16 }}}}>{{goal}}</p>
      <div style={{{{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 20 }}}}>
        <button
          type="button"
          onClick={{() => setTheme(theme === 'dark' ? 'light' : 'dark')}}
          style={{{{ padding: '8px 14px', borderRadius: 8, border: '1px solid #3a3a3a', background: '#111111', color: '#ffffff', cursor: 'pointer' }}}}
        >
          Toggle theme ({{theme}}) — persisted
        </button>
        <button
          type="button"
          onClick={{() => navigate('/dashboard')}}
          style={{{{ padding: '8px 14px', borderRadius: 8, background: '#ffffff', color: '#000000', border: 'none', cursor: 'pointer' }}}}
        >
          Go to Dashboard
        </button>
      </div>
      <p style={{{{ fontSize: 13, color: '#737373' }}}}>Theme and routes sync to localStorage via Zustand persist.</p>
    </div>
  );
}}
"""

    login = """import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export default function LoginPage() {
  const { login, isAuthenticated } = useAuth();
  const navigate = useNavigate();
  const [name, setName] = useState('');

  if (isAuthenticated) {
    navigate('/dashboard', { replace: true });
    return null;
  }

  return (
    <div style={{ maxWidth: 400 }}>
      <h1 style={{ marginBottom: 12 }}>Login (demo)</h1>
      <p style={{ color: '#8a8a8a', fontSize: 14, marginBottom: 16 }}>
        Client-only token stored in localStorage. Connect this flow to your API for production auth.
      </p>
      <input
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="Display name"
        style={{ width: '100%', padding: 10, borderRadius: 8, border: '1px solid #3a3a3a', background: '#111111', color: '#fff', marginBottom: 12 }}
      />
      <button
        type="button"
        onClick={() => { login(name || 'builder'); navigate('/dashboard'); }}
        style={{ padding: '10px 18px', borderRadius: 8, background: '#ffffff', color: '#000000', border: 'none', fontWeight: 600, cursor: 'pointer' }}
      >
        Sign in (demo)
      </button>
    </div>
  );
}
"""

    team_page = """import React from 'react';

export default function TeamPage() {
  return (
    <div>
      <h1 style={{ marginBottom: 12 }}>Team</h1>
      <p style={{ color: '#8a8a8a', lineHeight: 1.6 }}>
        Team directory route with starter content so routing and preview have a concrete page to render.
      </p>
    </div>
  );
}
"""

    dashboard = """import React from 'react';
import { Navigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useAppStore } from '../store/useAppStore';

export default function DashboardPage() {
  const { isAuthenticated, token, logout } = useAuth();
  const notes = useAppStore((s) => s.notes);
  const setNotes = useAppStore((s) => s.setNotes);

  if (!isAuthenticated) {
    return <Navigate to="/login" replace />;
  }

  return (
    <div>
      <h1 style={{ marginBottom: 8 }}>Dashboard</h1>
      <p style={{ color: '#8a8a8a', marginBottom: 16, wordBreak: 'break-all' }}>Token: {token.slice(0, 48)}…</p>
      <textarea
        value={notes}
        onChange={(e) => setNotes(e.target.value)}
        placeholder="Notes (persisted)"
        rows={4}
        style={{ width: '100%', padding: 10, borderRadius: 8, border: '1px solid #3a3a3a', background: '#111111', color: '#ffffff' }}
      />
      <button type="button" onClick={logout} style={{ marginTop: 12, padding: '8px 14px', borderRadius: 8, background: '#2a2a2a', color: '#fff', border: 'none', cursor: 'pointer' }}>
        Log out
      </button>
    </div>
  );
}
"""

    app = """import React from 'react';
import { MemoryRouter, Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider } from './context/AuthContext';
import ErrorBoundary from './components/ErrorBoundary';
import ShellLayout from './components/ShellLayout';
import HomePage from './pages/HomePage';
import LoginPage from './pages/LoginPage';
import DashboardPage from './pages/DashboardPage';
import TeamPage from './pages/TeamPage';

export default function App() {
  return (
    <ErrorBoundary>
      <AuthProvider>
        <MemoryRouter initialEntries={['/']}>
          <Routes>
            <Route element={<ShellLayout />}>
              <Route path="/" element={<HomePage />} />
              <Route path="/login" element={<LoginPage />} />
              <Route path="/dashboard" element={<DashboardPage />} />
              <Route path="/team" element={<TeamPage />} />
              {/* CRUCIB_APP_ROUTE_ANCHOR */}
              <Route path="*" element={<Navigate to="/" replace />} />
            </Route>
          </Routes>
        </MemoryRouter>
      </AuthProvider>
    </ErrorBoundary>
  );
}
"""

    index_html = """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CrucibAI Generated App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""

    vite_config = """import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
"""

    main_jsx = """import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import './styles/global.css';

const el = document.getElementById('root');
const root = createRoot(el);
root.render(<App />);
"""

    global_css = """@import './tokens.css';

* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: Inter, system-ui, sans-serif;
  background: var(--color-bg);
  color: var(--color-text);
}

.btn {
  border: 0;
  border-radius: var(--radius-md);
  cursor: pointer;
  padding: 10px 16px;
  transition: background var(--transition-fast), transform var(--transition-fast);
}
.btn:hover { transform: translateY(-1px); }
.btn-primary { background: var(--color-primary); color: #fff; }
.btn-secondary { background: var(--color-surface-2); color: var(--color-text); border: 1px solid var(--color-border); }
.field-input {
  width: 100%;
  padding: 10px 12px;
  border-radius: var(--radius-md);
  border: 1px solid var(--color-border);
  background: var(--color-surface-2);
  color: var(--color-text);
}
.surface-card, .content-panel {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-sm);
  padding: var(--space-6);
}
.badge { border: 1px solid var(--color-border); border-radius: 999px; padding: 3px 8px; color: var(--color-muted); }
.page-header { margin-bottom: var(--space-6); }
.page-header-row { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--space-4); }
.page-header p, .empty-state p { color: var(--color-muted); line-height: 1.6; }
.eyebrow { color: var(--color-primary); font-size: 12px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
.metric-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: var(--space-4); }
.metric-label { color: var(--color-muted); font-size: 13px; }
.metric-value { display: block; font-size: 28px; margin-top: var(--space-2); }
.metric-delta { color: var(--color-success); font-size: 13px; }
.table-wrap { overflow-x: auto; border: 1px solid var(--color-border); border-radius: var(--radius-lg); }
table { width: 100%; border-collapse: collapse; }
th, td { padding: 12px 14px; text-align: left; border-bottom: 1px solid var(--color-border); }
th { color: var(--color-muted); font-size: 12px; text-transform: uppercase; }
.empty-state { border: 1px dashed var(--color-border); border-radius: var(--radius-lg); padding: var(--space-6); }
.form-field { display: grid; gap: var(--space-2); color: var(--color-muted); }
.form-field small { color: #fca5a5; }
"""

    preview_contract = """import React from 'react';
import { MemoryRouter, Routes, Route } from 'react-router-dom';

/**
 * Contract-only marker component for preview verification.
 * It does not need to be mounted by the generated app, but it documents
 * that the workspace includes React Router primitives the preview gate expects.
 */
export default function PreviewContract() {
  return (
    <MemoryRouter initialEntries={['/']}>
      <Routes>
        <Route path="/" element={<div>Preview contract</div>} />
      </Routes>
    </MemoryRouter>
  );
}
"""

    out = [
        ("package.json", json.dumps(pkg, indent=2)),
        ("index.html", index_html),
        ("vite.config.js", vite_config),
        ("README.md", readme),
        ("README_BUILD.md", readme),
        ("src/store/useAppStore.js", store),
        ("src/context/AuthContext.jsx", auth),
        ("src/components/ErrorBoundary.jsx", error_boundary),
        ("src/components/ShellLayout.jsx", shell),
        ("src/pages/HomePage.jsx", home),
        ("src/pages/LoginPage.jsx", login),
        ("src/pages/DashboardPage.jsx", dashboard),
        ("src/pages/TeamPage.jsx", team_page),
        ("src/preview/PreviewContract.jsx", preview_contract),
        ("src/App.jsx", app),
        ("src/main.jsx", main_jsx),
        # Sandpack in Workspace.jsx expects /src/index.js; Vite uses main.jsx from index.html
        ("src/index.js", main_jsx),
        ("src/styles/global.css", global_css),
        ("docs/CRUCIB_BUILD_TARGET.md", _crucib_build_target_doc(job, target)),
    ]
    out.extend(_senior_structure_files(goal_raw))
    if target == "next_app_router":
        out.extend(_next_app_stub_files(goal_raw))
    if target == "mobile_expo":
        out.extend(_expo_mobile_stub_files(goal_raw))
    return out
