"""
PostgreSQL multitenant migration text — real RLS on generated app_items.

Session GUC: SET LOCAL app.tenant_id = '<uuid>' (or SELECT set_config('app.tenant_id', '<uuid>', true)).
FORCE ROW LEVEL SECURITY ensures policies apply even when the session user owns the table.
"""

from __future__ import annotations

from typing import Any, Dict, List

MULTITENANCY_MIGRATION_FILENAME = "002_multitenancy_rls.sql"

APP_ITEMS_DDL = """CREATE TABLE IF NOT EXISTS app_items (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);"""

_TENANTS_TABLE = """CREATE TABLE IF NOT EXISTS tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
)"""

_MULTITENANCY_RLS_DDL: list[str] = [
    "CREATE EXTENSION IF NOT EXISTS pgcrypto",
    _TENANTS_TABLE,
    "ALTER TABLE app_items ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id)",
    "CREATE INDEX IF NOT EXISTS idx_app_items_tenant_id ON app_items(tenant_id)",
    "ALTER TABLE app_items ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE app_items FORCE ROW LEVEL SECURITY",
    "DROP POLICY IF EXISTS app_items_select ON app_items",
    "DROP POLICY IF EXISTS app_items_insert ON app_items",
    "DROP POLICY IF EXISTS app_items_update ON app_items",
    "DROP POLICY IF EXISTS app_items_delete ON app_items",
    """CREATE POLICY app_items_select ON app_items
  FOR SELECT
  USING (
    tenant_id IS NOT NULL
    AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
  )""",
    """CREATE POLICY app_items_insert ON app_items
  FOR INSERT
  WITH CHECK (
    tenant_id IS NOT NULL
    AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
  )""",
    """CREATE POLICY app_items_update ON app_items
  FOR UPDATE
  USING (
    tenant_id IS NOT NULL
    AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
  )
  WITH CHECK (
    tenant_id IS NOT NULL
    AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
  )""",
    """CREATE POLICY app_items_delete ON app_items
  FOR DELETE
  USING (
    tenant_id IS NOT NULL
    AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
  )""",
]


def migration_001_app_schema_sql() -> str:
    return (
        "-- Generated by CrucibAI Auto-Runner (app schema sketch, not applied to host DB)\n"
        + APP_ITEMS_DDL
        + "\n"
    )


def migration_002_multitenancy_rls_sql() -> str:
    header = (
        f"-- {MULTITENANCY_MIGRATION_FILENAME} — apply after 001 (PostgreSQL)\n"
        "-- Live RLS: rows visible only when app.tenant_id matches tenant_id (session GUC).\n"
    )
    body = ";\n\n".join(s.strip().rstrip(";") for s in _MULTITENANCY_RLS_DDL) + ";\n"
    return header + body


def multitenancy_rls_ddl_statements() -> list[str]:
    """Same DDL as the migration file, for live DB tests (one executable statement each)."""
    return [s.strip().rstrip(";") + ";" for s in _MULTITENANCY_RLS_DDL]


def validate_rls_syntax(sql: str) -> Dict[str, Any]:
    """
    Static checks on migration text — not a substitute for live DB tests (see test_multitenancy_rls_live).
    Accepts NULLIF(current_setting('app.tenant_id', true), '')::uuid style used in generated migrations.
    """
    issues: List[str] = []
    proof: List[Dict[str, Any]] = []
    if not (sql or "").strip():
        issues.append("Empty SQL")
        return {"passed": False, "issues": issues, "proof": proof}

    u = sql.upper()
    lo = sql.lower()
    if "ENABLE ROW LEVEL SECURITY" not in u:
        issues.append("Missing ENABLE ROW LEVEL SECURITY")
    if "FORCE ROW LEVEL SECURITY" not in u:
        issues.append(
            "Missing FORCE ROW LEVEL SECURITY (table owner would bypass RLS without FORCE)"
        )
    if "CREATE POLICY" not in u:
        issues.append("No CREATE POLICY statements")
    if "tenant_id" not in lo:
        issues.append("Policies should reference tenant_id")
    if "current_setting" not in lo or "app.tenant_id" not in lo:
        issues.append("Missing session GUC current_setting('app.tenant_id', ...)")

    if not issues:
        proof.append(
            {
                "check": "rls_syntax_valid",
                "status": "pass",
                "note": "RLS migration structurally contains ENABLE/FORCE, CREATE POLICY, tenant_id, app.tenant_id GUC",
            },
        )

    return {"passed": len(issues) == 0, "issues": issues, "proof": proof}
